package wiktiopeggynary.model.meaning

/**
 * @author Krzysztof Witukiewicz
 */
class KontextShortcutMapper {

    def static final shortcuts = ['Akkusativ'   : 'mit Akkusativ',
                                  'mA'          : 'mit Akkusativ',
                                  'abw.'        : 'abwertend',
                                  'allg.'       : 'allgemein',
                                  'bar.'        : 'bairisch',
                                  'bair.'       : 'bairisch',
                                  'bildungsspr.': 'bildungssprachlich',
                                  'Dativ'       : 'mit Dativ',
                                  'mD'          : 'mit Dativ',
                                  'dichter.'    : 'dichterisch',
                                  'euph.'       : 'euphemistisch',
                                  'fachspr.'    : 'fachsprachlich',
                                  'fam.'        : 'familiär',
                                  'fig'         : 'figürlich',
                                  'fig.'        : 'figurativ',
                                  'geh.'        : 'gehoben',
                                  'Genitiv'     : 'mit Genitiv',
                                  'mG'          : 'mit Genitiv',
                                  'haben'       : '[[Hilfsverb]] [[haben]]',
                                  'hist.'       : 'historisch',
                                  'indekl.'     : 'indeklinabel',
                                  'Instrumental': 'mit Instrumental',
                                  'intrans.'    : 'intransitiv',
                                  'iron.'       : 'ironisch',
                                  'kPl.'        : 'kein [[Plural]]',
                                  'kSg.'        : 'kein [[Singular]]',
                                  'kSt.'        : 'keine Steigerung',
                                  'kStg.'       : 'keine Steigerung',
                                  'landsch.'    : 'landschaftlich',
                                  'lautm.'      : 'lautmalerisch',
                                  'Ling.'       : 'Linguistik',
                                  'mdal.'       : 'mundartlich',
                                  'mundartl.'   : 'mundartlich',
                                  'Med.'        : 'Medizin',
                                  'metaphor.'   : 'metaphorisch',
                                  'meton.'      : 'metonymisch',
                                  'nDu.'        : 'nur [[Dual]]',
                                  'nordd.'      : 'norddeutsch',
                                  'norddt.'     : 'norddeutsch',
                                  'nordwestd.'  : 'nordwestdeutsch',
                                  'nPl.'        : 'nur [[Plural]]',
                                  'österr.'     : 'österreichisch',
                                  'pej.'        : 'pejorativ',
                                  'poet.'       : 'poetisch',
                                  'Plural'      : 'im Plural',
                                  'iPl'         : 'im Plural',
                                  'Pl.'         : 'Plural',
                                  'Pl.1'        : 'Plural 1',
                                  'Pl.2'        : 'Plural 2',
                                  'reg.'        : 'regional',
                                  'refl.'       : 'reflexiv',
                                  'sal.'        : 'salopp',
                                  'scherzh.'    : 'scherzhaft',
                                  'schriftspr.' : 'schriftsprachlich',
                                  'schweiz.'    : 'schweizerisch',
                                  'sein'        : '[[Hilfsverb]] [[sein]]',
                                  'sonderspr.'  : '[[Sondersprache|sondersprachlich]]',
                                  'südd.'       : 'süddeutsch',
                                  'techn.'      : 'technisch',
                                  'trans.'      : 'transitiv',
                                  'übertr.'     : '[[im übertragenen Sinn|übertragen]]',
                                  'ugs.'        : 'umgangssprachlich',
                                  'unpers.'     : 'unpersönlich',
                                  'ungebr.'     : 'ungebräuchlich',
                                  'va.'         : 'veraltet',
                                  'veraltet'    : 'veraltet',
                                  'veraltend'   : 'veraltend',
                                  'tlwva.'      : 'veraltet',
                                  'vatd.'       : 'veraltend',
                                  'tlwvatd.'    : 'veraltend',
                                  'verh.'       : 'verhüllend',
                                  'volkst.'     : 'volkstümlich',
                                  'vul.'        : 'vulgär',
                                  'vulg.'       : 'vulgär']

    static Map<String, String> getShortcuts() {
        return Collections.unmodifiableMap(shortcuts)
    }
}
