//=========================================================================
//
//  This file was generated by Mouse 1.6.1 at 2015-08-24 17:58:38 GMT
//  from grammar
//    '/home/krzysiek/dev/projects/fiszki/wiktionary-parser/src/main/java/w
//    iktiopeggynary/parser/template/parser/../../../../../resources/templa
//    te_grammar.txt'.
//
//=========================================================================

package wiktiopeggynary.parser.template.parser;

import wiktiopeggynary.parser.mouse.Source;

public class TemplateParser extends wiktiopeggynary.parser.mouse.ParserMemo
{
  final TemplateSemantics sem;
  
  //=======================================================================
  //
  //  Initialization
  //
  //=======================================================================
  //-------------------------------------------------------------------
  //  Constructor
  //-------------------------------------------------------------------
  public TemplateParser()
    {
      sem = new TemplateSemantics();
      sem.rule = this;
      super.sem = sem;
      caches = cacheList;
    }
  
  //-------------------------------------------------------------------
  //  Run the parser
  //-------------------------------------------------------------------
  public boolean parse(Source src)
    {
      super.init(src);
      sem.init();
      if (TemplateDefinition()) return true;
      return failure();
    }
  
  //-------------------------------------------------------------------
  //  Get semantics
  //-------------------------------------------------------------------
  public TemplateSemantics semantics()
    { return sem; }
  
  //=======================================================================
  //
  //  Parsing procedures
  //
  //=======================================================================
  //=====================================================================
  //  TemplateDefinition = Space TemplateDefinitionComponent* EOF
  //    {TemplateDefinition} ;
  //=====================================================================
  private boolean TemplateDefinition()
    {
      if (saved(TemplateDefinition)) return reuse();
      Space();
      while (TemplateDefinitionComponent());
      if (!EOF()) return reject();
      sem.TemplateDefinition();
      return accept();
    }
  
  //=====================================================================
  //  TParam = LP Number (SEP DefaultValue)? RP Space {TParam_0} / LP
  //    TParamName (SEP DefaultValue)? RP Space {TParam_1} ;
  //=====================================================================
  private boolean TParam()
    {
      if (saved(TParam)) return reuse();
      if (TParam_0())
      { sem.TParam_0(); return accept(); }
      if (TParam_1())
      { sem.TParam_1(); return accept(); }
      return reject();
    }
  
  //-------------------------------------------------------------------
  //  TParam_0 = LP Number (SEP DefaultValue)? RP Space
  //-------------------------------------------------------------------
  private boolean TParam_0()
    {
      if (savedInner(TParam_0)) return reuseInner();
      if (!LP()) return rejectInner();
      if (!Number()) return rejectInner();
      TParam_2();
      if (!RP()) return rejectInner();
      Space();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TParam_1 = LP TParamName (SEP DefaultValue)? RP Space
  //-------------------------------------------------------------------
  private boolean TParam_1()
    {
      if (savedInner(TParam_1)) return reuseInner();
      if (!LP()) return rejectInner();
      if (!TParamName()) return rejectInner();
      TParam_2();
      if (!RP()) return rejectInner();
      Space();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TParam_2 = SEP DefaultValue
  //-------------------------------------------------------------------
  private boolean TParam_2()
    {
      if (savedInner(TParam_2)) return reuseInner();
      if (!SEP()) return rejectInner();
      DefaultValue();
      return acceptInner();
    }
  
  //=====================================================================
  //  TParamName = (!(SEP / RP) _)+ ;
  //=====================================================================
  private boolean TParamName()
    {
      if (saved(TParamName)) return reuse();
      if (!TParamName_0()) return reject();
      while (TParamName_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  TParamName_0 = !(SEP / RP) _
  //-------------------------------------------------------------------
  private boolean TParamName_0()
    {
      if (savedInner(TParamName_0)) return reuseInner();
      if (!TParamName_1()) return rejectInner();
      if (!next()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TParamName_1 = !(SEP / RP)
  //-------------------------------------------------------------------
  private boolean TParamName_1()
    {
      if (savedInner(TParamName_1)) return reusePred();
      if (TParamName_2()) return rejectNot();
      return acceptNot();
    }
  
  //-------------------------------------------------------------------
  //  TParamName_2 = SEP / RP
  //-------------------------------------------------------------------
  private boolean TParamName_2()
    {
      if (savedInner(TParamName_2)) return reuseInner();
      if (SEP()) return acceptInner();
      if (RP()) return acceptInner();
      return rejectInner();
    }
  
  //=====================================================================
  //  DefaultValue = (!RP _)* ;
  //=====================================================================
  private boolean DefaultValue()
    {
      if (saved(DefaultValue)) return reuse();
      while (DefaultValue_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  DefaultValue_0 = !RP _
  //-------------------------------------------------------------------
  private boolean DefaultValue_0()
    {
      if (savedInner(DefaultValue_0)) return reuseInner();
      if (!DefaultValue_1()) return rejectInner();
      if (!next()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  DefaultValue_1 = !RP
  //-------------------------------------------------------------------
  private boolean DefaultValue_1()
    {
      if (savedInner(DefaultValue_1)) return reusePred();
      if (RP()) return rejectNot();
      return acceptNot();
    }
  
  //=====================================================================
  //  Function = LF "#" FName ":" FParam (SEP FParam)* RF {Function} ;
  //=====================================================================
  private boolean Function()
    {
      if (saved(Function)) return reuse();
      if (!LF()) return reject();
      if (!next('#')) return reject();
      if (!FName()) return reject();
      if (!next(':')) return reject();
      FParam();
      while (Function_0());
      if (!RF()) return reject();
      sem.Function();
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  Function_0 = SEP FParam
  //-------------------------------------------------------------------
  private boolean Function_0()
    {
      if (savedInner(Function_0)) return reuseInner();
      if (!SEP()) return rejectInner();
      FParam();
      return acceptInner();
    }
  
  //=====================================================================
  //  FName = (!COL _)+ ;
  //=====================================================================
  private boolean FName()
    {
      if (saved(FName)) return reuse();
      if (!FName_0()) return reject();
      while (FName_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  FName_0 = !COL _
  //-------------------------------------------------------------------
  private boolean FName_0()
    {
      if (savedInner(FName_0)) return reuseInner();
      if (!FName_1()) return rejectInner();
      if (!next()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  FName_1 = !COL
  //-------------------------------------------------------------------
  private boolean FName_1()
    {
      if (savedInner(FName_1)) return reusePred();
      if (COL()) return rejectNot();
      return acceptNot();
    }
  
  //=====================================================================
  //  FParam = Space (!(SEP / RF) TemplateDefinitionComponent)* {FParam}
  //    ;
  //=====================================================================
  private boolean FParam()
    {
      if (saved(FParam)) return reuse();
      Space();
      while (FParam_0());
      sem.FParam();
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  FParam_0 = !(SEP / RF) TemplateDefinitionComponent
  //-------------------------------------------------------------------
  private boolean FParam_0()
    {
      if (savedInner(FParam_0)) return reuseInner();
      if (!FParam_1()) return rejectInner();
      if (!TemplateDefinitionComponent()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  FParam_1 = !(SEP / RF)
  //-------------------------------------------------------------------
  private boolean FParam_1()
    {
      if (savedInner(FParam_1)) return reusePred();
      if (FParam_2()) return rejectNot();
      return acceptNot();
    }
  
  //-------------------------------------------------------------------
  //  FParam_2 = SEP / RF
  //-------------------------------------------------------------------
  private boolean FParam_2()
    {
      if (savedInner(FParam_2)) return reuseInner();
      if (SEP()) return acceptInner();
      if (RF()) return acceptInner();
      return rejectInner();
    }
  
  //=====================================================================
  //  SwitchFunction = LF "#switch:" FParam (SEP SwitchTestCase)+ RF
  //    {SwitchFunction} ;
  //=====================================================================
  private boolean SwitchFunction()
    {
      if (saved(SwitchFunction)) return reuse();
      if (!LF()) return reject();
      if (!next("#switch:")) return reject();
      FParam();
      if (!SwitchFunction_0()) return reject();
      while (SwitchFunction_0());
      if (!RF()) return reject();
      sem.SwitchFunction();
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  SwitchFunction_0 = SEP SwitchTestCase
  //-------------------------------------------------------------------
  private boolean SwitchFunction_0()
    {
      if (savedInner(SwitchFunction_0)) return reuseInner();
      if (!SEP()) return rejectInner();
      if (!SwitchTestCase()) return rejectInner();
      return acceptInner();
    }
  
  //=====================================================================
  //  SwitchTestCase = "#default" Space EQ FParam {SwitchTestCase_0} /
  //    SwitchTest Space &RF {SwitchTestCase_1} / SwitchTest (EQ FParam)?
  //    {SwitchTestCase_2} ;
  //=====================================================================
  private boolean SwitchTestCase()
    {
      if (saved(SwitchTestCase)) return reuse();
      if (SwitchTestCase_0())
      { sem.SwitchTestCase_0(); return accept(); }
      if (SwitchTestCase_1())
      { sem.SwitchTestCase_1(); return accept(); }
      if (SwitchTestCase_2())
      { sem.SwitchTestCase_2(); return accept(); }
      return reject();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTestCase_0 = "#default" Space EQ FParam
  //-------------------------------------------------------------------
  private boolean SwitchTestCase_0()
    {
      if (savedInner(SwitchTestCase_0)) return reuseInner();
      if (!next("#default")) return rejectInner();
      Space();
      if (!EQ()) return rejectInner();
      FParam();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTestCase_1 = SwitchTest Space &RF
  //-------------------------------------------------------------------
  private boolean SwitchTestCase_1()
    {
      if (savedInner(SwitchTestCase_1)) return reuseInner();
      if (!SwitchTest()) return rejectInner();
      Space();
      if (!SwitchTestCase_3()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTestCase_2 = SwitchTest (EQ FParam)?
  //-------------------------------------------------------------------
  private boolean SwitchTestCase_2()
    {
      if (savedInner(SwitchTestCase_2)) return reuseInner();
      if (!SwitchTest()) return rejectInner();
      SwitchTestCase_4();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTestCase_3 = &RF
  //-------------------------------------------------------------------
  private boolean SwitchTestCase_3()
    {
      if (savedInner(SwitchTestCase_3)) return reusePred();
      if (!RF()) return rejectAnd();
      return acceptAnd();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTestCase_4 = EQ FParam
  //-------------------------------------------------------------------
  private boolean SwitchTestCase_4()
    {
      if (savedInner(SwitchTestCase_4)) return reuseInner();
      if (!EQ()) return rejectInner();
      FParam();
      return acceptInner();
    }
  
  //=====================================================================
  //  SwitchTest = (!(SEP / RF / EQ) TemplateDefinitionComponent)+
  //    {SwitchTest} ;
  //=====================================================================
  private boolean SwitchTest()
    {
      if (saved(SwitchTest)) return reuse();
      if (!SwitchTest_0()) return reject();
      while (SwitchTest_0());
      sem.SwitchTest();
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTest_0 = !(SEP / RF / EQ) TemplateDefinitionComponent
  //-------------------------------------------------------------------
  private boolean SwitchTest_0()
    {
      if (savedInner(SwitchTest_0)) return reuseInner();
      if (!SwitchTest_1()) return rejectInner();
      if (!TemplateDefinitionComponent()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTest_1 = !(SEP / RF / EQ)
  //-------------------------------------------------------------------
  private boolean SwitchTest_1()
    {
      if (savedInner(SwitchTest_1)) return reusePred();
      if (SwitchTest_2()) return rejectNot();
      return acceptNot();
    }
  
  //-------------------------------------------------------------------
  //  SwitchTest_2 = SEP / RF / EQ
  //-------------------------------------------------------------------
  private boolean SwitchTest_2()
    {
      if (savedInner(SwitchTest_2)) return reuseInner();
      if (SEP()) return acceptInner();
      if (RF()) return acceptInner();
      if (EQ()) return acceptInner();
      return rejectInner();
    }
  
  //=====================================================================
  //  TemplateDefinitionComponent = TParam
  //    {TemplateDefinitionComponent_0} / (SwitchFunction / Function)
  //    {TemplateDefinitionComponent_1} / TemplateCall
  //    {TemplateDefinitionComponent_2} / (NoInclude / IncludeOnly /
  //    Comment) / _ {TemplateDefinitionComponent_4} ;
  //=====================================================================
  private boolean TemplateDefinitionComponent()
    {
      if (saved(TemplateDefinitionComponent)) return reuse();
      if (TParam())
      { sem.TemplateDefinitionComponent_0(); return accept(); }
      if (TemplateDefinitionComponent_0())
      { sem.TemplateDefinitionComponent_1(); return accept(); }
      if (TemplateCall())
      { sem.TemplateDefinitionComponent_2(); return accept(); }
      if (TemplateDefinitionComponent_1()) return accept();
      if (next())
      { sem.TemplateDefinitionComponent_4(); return accept(); }
      return reject();
    }
  
  //-------------------------------------------------------------------
  //  TemplateDefinitionComponent_0 = SwitchFunction / Function
  //-------------------------------------------------------------------
  private boolean TemplateDefinitionComponent_0()
    {
      if (savedInner(TemplateDefinitionComponent_0)) return reuseInner();
      if (SwitchFunction()) return acceptInner();
      if (Function()) return acceptInner();
      return rejectInner();
    }
  
  //-------------------------------------------------------------------
  //  TemplateDefinitionComponent_1 = NoInclude / IncludeOnly /
  //    Comment
  //-------------------------------------------------------------------
  private boolean TemplateDefinitionComponent_1()
    {
      if (savedInner(TemplateDefinitionComponent_1)) return reuseInner();
      if (NoInclude()) return acceptInner();
      if (IncludeOnly()) return acceptInner();
      if (Comment()) return acceptInner();
      return rejectInner();
    }
  
  //=====================================================================
  //  NoInclude = "<noinclude>" _*+ "</noinclude>" ;
  //=====================================================================
  private boolean NoInclude()
    {
      if (saved(NoInclude)) return reuse();
      if (!next("<noinclude>")) return reject();
      while (!next("</noinclude>"))
        if (!next()) return reject();
      return accept();
    }
  
  //=====================================================================
  //  IncludeOnly = "<includeonly>" _*+ "</includeonly>" ;
  //=====================================================================
  private boolean IncludeOnly()
    {
      if (saved(IncludeOnly)) return reuse();
      if (!next("<includeonly>")) return reject();
      while (!next("</includeonly>"))
        if (!next()) return reject();
      return accept();
    }
  
  //=====================================================================
  //  TemplateCall = LF TName (SEP TCallParam)* RF {TemplateCall} ;
  //=====================================================================
  private boolean TemplateCall()
    {
      if (saved(TemplateCall)) return reuse();
      if (!LF()) return reject();
      if (!TName()) return reject();
      while (TemplateCall_0());
      if (!RF()) return reject();
      sem.TemplateCall();
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  TemplateCall_0 = SEP TCallParam
  //-------------------------------------------------------------------
  private boolean TemplateCall_0()
    {
      if (savedInner(TemplateCall_0)) return reuseInner();
      if (!SEP()) return rejectInner();
      TCallParam();
      return acceptInner();
    }
  
  //=====================================================================
  //  TName = (!(SEP / RF) _)+ ;
  //=====================================================================
  private boolean TName()
    {
      if (saved(TName)) return reuse();
      if (!TName_0()) return reject();
      while (TName_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  TName_0 = !(SEP / RF) _
  //-------------------------------------------------------------------
  private boolean TName_0()
    {
      if (savedInner(TName_0)) return reuseInner();
      if (!FParam_1()) return rejectInner();
      if (!next()) return rejectInner();
      return acceptInner();
    }
  
  //=====================================================================
  //  TCallParam = Number EQ (!(SEP / RF) TemplateDefinitionComponent)*
  //    {TCallParam_0} / TCallParamName EQ (!(SEP / RF)
  //    TemplateDefinitionComponent)* {TCallParam_1} / (!(SEP / RF)
  //    TemplateDefinitionComponent)* {TCallParam_2} ;
  //=====================================================================
  private boolean TCallParam()
    {
      if (saved(TCallParam)) return reuse();
      if (TCallParam_0())
      { sem.TCallParam_0(); return accept(); }
      if (TCallParam_1())
      { sem.TCallParam_1(); return accept(); }
      if (TCallParam_2())
      { sem.TCallParam_2(); return accept(); }
      return reject();
    }
  
  //-------------------------------------------------------------------
  //  TCallParam_0 = Number EQ (!(SEP / RF)
  //    TemplateDefinitionComponent)*
  //-------------------------------------------------------------------
  private boolean TCallParam_0()
    {
      if (savedInner(TCallParam_0)) return reuseInner();
      if (!Number()) return rejectInner();
      if (!EQ()) return rejectInner();
      while (FParam_0());
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TCallParam_1 = TCallParamName EQ (!(SEP / RF)
  //    TemplateDefinitionComponent)*
  //-------------------------------------------------------------------
  private boolean TCallParam_1()
    {
      if (savedInner(TCallParam_1)) return reuseInner();
      if (!TCallParamName()) return rejectInner();
      if (!EQ()) return rejectInner();
      while (FParam_0());
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TCallParam_2 = (!(SEP / RF) TemplateDefinitionComponent)*
  //-------------------------------------------------------------------
  private boolean TCallParam_2()
    {
      if (savedInner(TCallParam_2)) return reuseInner();
      while (FParam_0());
      return acceptInner();
    }
  
  //=====================================================================
  //  TCallParamName = (!EQ _)+ ;
  //=====================================================================
  private boolean TCallParamName()
    {
      if (saved(TCallParamName)) return reuse();
      if (!TCallParamName_0()) return reject();
      while (TCallParamName_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  TCallParamName_0 = !EQ _
  //-------------------------------------------------------------------
  private boolean TCallParamName_0()
    {
      if (savedInner(TCallParamName_0)) return reuseInner();
      if (!TCallParamName_1()) return rejectInner();
      if (!next()) return rejectInner();
      return acceptInner();
    }
  
  //-------------------------------------------------------------------
  //  TCallParamName_1 = !EQ
  //-------------------------------------------------------------------
  private boolean TCallParamName_1()
    {
      if (savedInner(TCallParamName_1)) return reusePred();
      if (EQ()) return rejectNot();
      return acceptNot();
    }
  
  //=====================================================================
  //  LP = "{{{" ;
  //=====================================================================
  private boolean LP()
    {
      if (saved(LP)) return reuse();
      if (!next("{{{")) return reject();
      return accept();
    }
  
  //=====================================================================
  //  RP = "}}}" ;
  //=====================================================================
  private boolean RP()
    {
      if (saved(RP)) return reuse();
      if (!next("}}}")) return reject();
      return accept();
    }
  
  //=====================================================================
  //  LF = "{{" Space ;
  //=====================================================================
  private boolean LF()
    {
      if (saved(LF)) return reuse();
      if (!next("{{")) return reject();
      Space();
      return accept();
    }
  
  //=====================================================================
  //  RF = Space "}}" Space ;
  //=====================================================================
  private boolean RF()
    {
      if (saved(RF)) return reuse();
      Space();
      if (!next("}}")) return reject();
      Space();
      return accept();
    }
  
  //=====================================================================
  //  SEP = Space "|" Space ;
  //=====================================================================
  private boolean SEP()
    {
      if (saved(SEP)) return reuse();
      Space();
      if (!next('|')) return reject();
      Space();
      return accept();
    }
  
  //=====================================================================
  //  EQ = Space "=" Space ;
  //=====================================================================
  private boolean EQ()
    {
      if (saved(EQ)) return reuse();
      Space();
      if (!next('=')) return reject();
      Space();
      return accept();
    }
  
  //=====================================================================
  //  COL = Space ":" Space ;
  //=====================================================================
  private boolean COL()
    {
      if (saved(COL)) return reuse();
      Space();
      if (!next(':')) return reject();
      Space();
      return accept();
    }
  
  //=====================================================================
  //  Number = Digit+ ;
  //=====================================================================
  private boolean Number()
    {
      if (saved(Number)) return reuse();
      if (!Digit()) return reject();
      while (Digit());
      return accept();
    }
  
  //=====================================================================
  //  Digit = [0-9] ;
  //=====================================================================
  private boolean Digit()
    {
      if (saved(Digit)) return reuse();
      if (!nextIn('0','9')) return reject();
      return accept();
    }
  
  //=====================================================================
  //  Letter = [a-z] / [A-Z] / [äÄüÜöÖß] ;
  //=====================================================================
  private boolean Letter()
    {
      if (saved(Letter)) return reuse();
      if (nextIn('a','z')) return accept();
      if (nextIn('A','Z')) return accept();
      if (nextIn("\u00e4\u00c4\u00fc\u00dc\u00f6\u00d6\u00df")) return accept();
      return reject();
    }
  
  //=====================================================================
  //  Space = (" " / EOL / Comment)* ;
  //=====================================================================
  private boolean Space()
    {
      if (saved(Space)) return reuse();
      while (Space_0());
      return accept();
    }
  
  //-------------------------------------------------------------------
  //  Space_0 = " " / EOL / Comment
  //-------------------------------------------------------------------
  private boolean Space_0()
    {
      if (savedInner(Space_0)) return reuseInner();
      if (next(' ')) return acceptInner();
      if (EOL()) return acceptInner();
      if (Comment()) return acceptInner();
      return rejectInner();
    }
  
  //=====================================================================
  //  Comment = "<!--" _++ "-->" ;
  //=====================================================================
  private boolean Comment()
    {
      if (saved(Comment)) return reuse();
      if (!next("<!--")) return reject();
      if (next("-->")) return reject();
      do if (!next()) return reject();
        while (!next("-->"));
      return accept();
    }
  
  //=====================================================================
  //  EOF = !_ ;
  //=====================================================================
  private boolean EOF()
    {
      if (saved(EOF)) return reuse();
      if (!aheadNot()) return reject();
      return accept();
    }
  
  //=====================================================================
  //  EOL = [\r\n]+ ;
  //=====================================================================
  private boolean EOL()
    {
      if (saved(EOL)) return reuse();
      if (!nextIn("\r\n")) return reject();
      while (nextIn("\r\n"));
      return accept();
    }
  
  //=======================================================================
  //
  //  Cache objects
  //
  //=======================================================================
  
  final Cache TemplateDefinition = new Cache("TemplateDefinition","TemplateDefinition");
  final Cache TParam = new Cache("TParam","TParam");
  final Cache TParamName = new Cache("TParamName","TParamName");
  final Cache DefaultValue = new Cache("DefaultValue","DefaultValue");
  final Cache Function = new Cache("Function","Function");
  final Cache FName = new Cache("FName","FName");
  final Cache FParam = new Cache("FParam","FParam");
  final Cache SwitchFunction = new Cache("SwitchFunction","SwitchFunction");
  final Cache SwitchTestCase = new Cache("SwitchTestCase","SwitchTestCase");
  final Cache SwitchTest = new Cache("SwitchTest","SwitchTest");
  final Cache TemplateDefinitionComponent = new Cache("TemplateDefinitionComponent","TemplateDefinitionComponent");
  final Cache NoInclude = new Cache("NoInclude","NoInclude");
  final Cache IncludeOnly = new Cache("IncludeOnly","IncludeOnly");
  final Cache TemplateCall = new Cache("TemplateCall","TemplateCall");
  final Cache TName = new Cache("TName","TName");
  final Cache TCallParam = new Cache("TCallParam","TCallParam");
  final Cache TCallParamName = new Cache("TCallParamName","TCallParamName");
  final Cache LP = new Cache("LP","LP");
  final Cache RP = new Cache("RP","RP");
  final Cache LF = new Cache("LF","LF");
  final Cache RF = new Cache("RF","RF");
  final Cache SEP = new Cache("SEP","SEP");
  final Cache EQ = new Cache("EQ","EQ");
  final Cache COL = new Cache("COL","COL");
  final Cache Number = new Cache("Number","Number");
  final Cache Digit = new Cache("Digit","Digit");
  final Cache Letter = new Cache("Letter","Letter");
  final Cache Space = new Cache("Space","Space");
  final Cache Comment = new Cache("Comment","Comment");
  final Cache EOF = new Cache("EOF","EOF");
  final Cache EOL = new Cache("EOL","EOL");
  
  final Cache TParam_0 = new Cache("TParam_0"); // LP Number (SEP DefaultValue)? RP Space
  final Cache TParam_1 = new Cache("TParam_1"); // LP TParamName (SEP DefaultValue)? RP Space
  final Cache TParam_2 = new Cache("TParam_2"); // SEP DefaultValue
  final Cache TParamName_0 = new Cache("TParamName_0"); // !(SEP / RP) _
  final Cache TParamName_1 = new Cache("TParamName_1","not SEP / RP"); // !(SEP / RP)
  final Cache TParamName_2 = new Cache("TParamName_2"); // SEP / RP
  final Cache DefaultValue_0 = new Cache("DefaultValue_0"); // !RP _
  final Cache DefaultValue_1 = new Cache("DefaultValue_1","not RP"); // !RP
  final Cache Function_0 = new Cache("Function_0"); // SEP FParam
  final Cache FName_0 = new Cache("FName_0"); // !COL _
  final Cache FName_1 = new Cache("FName_1","not COL"); // !COL
  final Cache FParam_0 = new Cache("FParam_0"); // !(SEP / RF) TemplateDefinitionComponent
  final Cache FParam_1 = new Cache("FParam_1","not SEP / RF"); // !(SEP / RF)
  final Cache FParam_2 = new Cache("FParam_2"); // SEP / RF
  final Cache SwitchFunction_0 = new Cache("SwitchFunction_0"); // SEP SwitchTestCase
  final Cache SwitchTestCase_0 = new Cache("SwitchTestCase_0"); // "#default" Space EQ FParam
  final Cache SwitchTestCase_1 = new Cache("SwitchTestCase_1"); // SwitchTest Space &RF
  final Cache SwitchTestCase_2 = new Cache("SwitchTestCase_2"); // SwitchTest (EQ FParam)?
  final Cache SwitchTestCase_3 = new Cache("SwitchTestCase_3","RF"); // &RF
  final Cache SwitchTestCase_4 = new Cache("SwitchTestCase_4"); // EQ FParam
  final Cache SwitchTest_0 = new Cache("SwitchTest_0"); // !(SEP / RF / EQ) TemplateDefinitionComponent
  final Cache SwitchTest_1 = new Cache("SwitchTest_1","not SEP / RF / EQ"); // !(SEP / RF / EQ)
  final Cache SwitchTest_2 = new Cache("SwitchTest_2"); // SEP / RF / EQ
  final Cache TemplateDefinitionComponent_0 = new Cache("TemplateDefinitionComponent_0"); // SwitchFunction / Function
  final Cache TemplateDefinitionComponent_1 = new Cache("TemplateDefinitionComponent_1"); // NoInclude / IncludeOnly / Comment
  final Cache TemplateCall_0 = new Cache("TemplateCall_0"); // SEP TCallParam
  final Cache TName_0 = new Cache("TName_0"); // !(SEP / RF) _
  final Cache TCallParam_0 = new Cache("TCallParam_0"); // Number EQ (!(SEP / RF) TemplateDefinitionComponent)*
  final Cache TCallParam_1 = new Cache("TCallParam_1"); // TCallParamName EQ (!(SEP / RF) TemplateDefinitionComponent)*
  final Cache TCallParam_2 = new Cache("TCallParam_2"); // (!(SEP / RF) TemplateDefinitionComponent)*
  final Cache TCallParamName_0 = new Cache("TCallParamName_0"); // !EQ _
  final Cache TCallParamName_1 = new Cache("TCallParamName_1","not EQ"); // !EQ
  final Cache Space_0 = new Cache("Space_0"); // " " / EOL / Comment
  
  //-------------------------------------------------------------------
  //  List of Cache objects
  //-------------------------------------------------------------------
  
  Cache[] cacheList =
  {
    TemplateDefinition,TParam,TParamName,DefaultValue,Function,FName,
    FParam,SwitchFunction,SwitchTestCase,SwitchTest,
    TemplateDefinitionComponent,NoInclude,IncludeOnly,TemplateCall,
    TName,TCallParam,TCallParamName,LP,RP,LF,RF,SEP,EQ,COL,Number,
    Digit,Letter,Space,Comment,EOF,EOL,TParam_0,TParam_1,TParam_2,
    TParamName_0,TParamName_1,TParamName_2,DefaultValue_0,
    DefaultValue_1,Function_0,FName_0,FName_1,FParam_0,FParam_1,
    FParam_2,SwitchFunction_0,SwitchTestCase_0,SwitchTestCase_1,
    SwitchTestCase_2,SwitchTestCase_3,SwitchTestCase_4,SwitchTest_0,
    SwitchTest_1,SwitchTest_2,TemplateDefinitionComponent_0,
    TemplateDefinitionComponent_1,TemplateCall_0,TName_0,TCallParam_0,
    TCallParam_1,TCallParam_2,TCallParamName_0,TCallParamName_1,
    Space_0
  };
}
