//=========================================================================
//
//  This file was generated by Mouse 1.6.1 at 2015-08-24 15:56:36 GMT
//  from grammar
//    '/home/krzysiek/dev/projects/fiszki/wiktionary-parser/src/main/java/w
//    iktiopeggynary/parser/../../../resources/entry_grammar.txt'.
//
//=========================================================================

package wiktiopeggynary.parser;

import wiktiopeggynary.parser.mouse.Source;

public class WiktionaryParser extends wiktiopeggynary.parser.mouse.ParserTest
{
  final WiktionarySemantics sem;
  
  //=======================================================================
  //
  //  Initialization
  //
  //=======================================================================
  //-------------------------------------------------------------------
  //  Constructor
  //-------------------------------------------------------------------
  public WiktionaryParser()
    {
      sem = new WiktionarySemantics();
      sem.rule = this;
      super.sem = sem;
      caches = cacheList;
    }
  
  //-------------------------------------------------------------------
  //  Run the parser
  //-------------------------------------------------------------------
  public boolean parse(Source src)
    {
      super.init(src);
      sem.init();
      if (Dokument()) return true;
      return failure();
    }
  
  //-------------------------------------------------------------------
  //  Get semantics
  //-------------------------------------------------------------------
  public WiktionarySemantics semantics()
    { return sem; }
  
  //=======================================================================
  //
  //  Parsing procedures
  //
  //=======================================================================
  //=====================================================================
  //  Dokument = (!KOPF2 Line)* Eintrag EOF ;
  //=====================================================================
  private boolean Dokument()
    {
      if (saved(Dokument)) return reuse();
      while (Dokument_0());
      if (!Eintrag()) return reject(Dokument);
      if (!EOF()) return reject(Dokument);
      return accept(Dokument);
    }
  
  //-------------------------------------------------------------------
  //  Dokument_0 = !KOPF2 Line
  //-------------------------------------------------------------------
  private boolean Dokument_0()
    {
      if (savedInner(Dokument_0)) return reuseInner();
      if (!Dokument_1()) return rejectInner(Dokument_0);
      if (!Line()) return rejectInner(Dokument_0);
      return acceptInner(Dokument_0);
    }
  
  //-------------------------------------------------------------------
  //  Dokument_1 = !KOPF2
  //-------------------------------------------------------------------
  private boolean Dokument_1()
    {
      if (savedInner(Dokument_1)) return reusePred();
      if (KOPF2()) return rejectNot(Dokument_1);
      return acceptNot(Dokument_1);
    }
  
  //=====================================================================
  //  Eintrag = DeEintrag? OtherLangEintrag* EOF ;
  //=====================================================================
  private boolean Eintrag()
    {
      if (saved(Eintrag)) return reuse();
      DeEintrag();
      while (OtherLangEintrag());
      if (!EOF()) return reject(Eintrag);
      return accept(Eintrag);
    }
  
  //=====================================================================
  //  OtherLangEintrag = (!DeSpracheKopf Line)+ ;
  //=====================================================================
  private boolean OtherLangEintrag()
    {
      if (saved(OtherLangEintrag)) return reuse();
      if (!OtherLangEintrag_0()) return reject(OtherLangEintrag);
      while (OtherLangEintrag_0());
      return accept(OtherLangEintrag);
    }
  
  //-------------------------------------------------------------------
  //  OtherLangEintrag_0 = !DeSpracheKopf Line
  //-------------------------------------------------------------------
  private boolean OtherLangEintrag_0()
    {
      if (savedInner(OtherLangEintrag_0)) return reuseInner();
      if (!OtherLangEintrag_1()) return rejectInner(OtherLangEintrag_0);
      if (!Line()) return rejectInner(OtherLangEintrag_0);
      return acceptInner(OtherLangEintrag_0);
    }
  
  //-------------------------------------------------------------------
  //  OtherLangEintrag_1 = !DeSpracheKopf
  //-------------------------------------------------------------------
  private boolean OtherLangEintrag_1()
    {
      if (savedInner(OtherLangEintrag_1)) return reusePred();
      if (DeSpracheKopf()) return rejectNot(OtherLangEintrag_1);
      return acceptNot(OtherLangEintrag_1);
    }
  
  //=====================================================================
  //  DeEintrag = DeSpracheKopf DeWortart+ ;
  //=====================================================================
  private boolean DeEintrag()
    {
      if (saved(DeEintrag)) return reuse();
      if (!DeSpracheKopf()) return reject(DeEintrag);
      if (!DeWortart()) return reject(DeEintrag);
      while (DeWortart());
      return accept(DeEintrag);
    }
  
  //=====================================================================
  //  DeSpracheKopf = KOPF2 Lemma "(" DeSpracheTemplate ")" Space KOPF2
  //    RestOfLine ;
  //=====================================================================
  private boolean DeSpracheKopf()
    {
      if (saved(DeSpracheKopf)) return reuse();
      if (!KOPF2()) return reject(DeSpracheKopf);
      if (!Lemma()) return reject(DeSpracheKopf);
      if (!next('(',$Term11)) return reject(DeSpracheKopf);
      if (!DeSpracheTemplate()) return reject(DeSpracheKopf);
      if (!next(')',$Term60)) return reject(DeSpracheKopf);
      Space();
      if (!KOPF2()) return reject(DeSpracheKopf);
      if (!RestOfLine()) return reject(DeSpracheKopf);
      return accept(DeSpracheKopf);
    }
  
  //=====================================================================
  //  DeSpracheTemplate = LT "Sprache" SEP "Deutsch" RT ;
  //=====================================================================
  private boolean DeSpracheTemplate()
    {
      if (saved(DeSpracheTemplate)) return reuse();
      if (!LT()) return reject(DeSpracheTemplate);
      if (!next("Sprache",$Term18)) return reject(DeSpracheTemplate);
      if (!SEP()) return reject(DeSpracheTemplate);
      if (!next("Deutsch",$Term46)) return reject(DeSpracheTemplate);
      if (!RT()) return reject(DeSpracheTemplate);
      return accept(DeSpracheTemplate);
    }
  
  //=====================================================================
  //  Lemma = Letter+ Space {Lemma} ;
  //=====================================================================
  private boolean Lemma()
    {
      if (saved(Lemma)) return reuse();
      if (!Letter()) return reject(Lemma);
      while (Letter());
      Space();
      sem.Lemma();
      return accept(Lemma);
    }
  
  //=====================================================================
  //  DeWortart = (WortartKopf WortartBody / UnknownWortartKopf Line*) ;
  //=====================================================================
  private boolean DeWortart()
    {
      if (saved(DeWortart)) return reuse();
      if (!DeWortart_0()
       && !DeWortart_1()
         ) return reject(DeWortart);
      return accept(DeWortart);
    }
  
  //-------------------------------------------------------------------
  //  DeWortart_0 = WortartKopf WortartBody
  //-------------------------------------------------------------------
  private boolean DeWortart_0()
    {
      if (savedInner(DeWortart_0)) return reuseInner();
      if (!WortartKopf()) return rejectInner(DeWortart_0);
      WortartBody();
      return acceptInner(DeWortart_0);
    }
  
  //-------------------------------------------------------------------
  //  DeWortart_1 = UnknownWortartKopf Line*
  //-------------------------------------------------------------------
  private boolean DeWortart_1()
    {
      if (savedInner(DeWortart_1)) return reuseInner();
      if (!UnknownWortartKopf()) return rejectInner(DeWortart_1);
      while (Line());
      return acceptInner(DeWortart_1);
    }
  
  //=====================================================================
  //  WortartKopf = SubstantivKopf {saveEintrag} ;
  //=====================================================================
  private boolean WortartKopf()
    {
      if (saved(WortartKopf)) return reuse();
      if (!SubstantivKopf()) return reject(WortartKopf);
      sem.saveEintrag();
      return accept(WortartKopf);
    }
  
  //=====================================================================
  //  WortartBody = MiddleSection TranslationsSection?
  //    ~{WortartBody_fail} ;
  //=====================================================================
  private boolean WortartBody()
    {
      if (saved(WortartBody)) return reuse();
      if (WortartBody_0()) return accept(WortartBody);
      else sem.WortartBody_fail();
      return reject(WortartBody);
    }
  
  //-------------------------------------------------------------------
  //  WortartBody_0 = MiddleSection TranslationsSection?
  //-------------------------------------------------------------------
  private boolean WortartBody_0()
    {
      if (savedInner(WortartBody_0)) return reuseInner();
      MiddleSection();
      TranslationsSection();
      return acceptInner(WortartBody_0);
    }
  
  //=====================================================================
  //  UnknownWortartKopf = KOPF3 WortartTemplate _*+ KOPF3 RestOfLine ;
  //=====================================================================
  private boolean UnknownWortartKopf()
    {
      if (saved(UnknownWortartKopf)) return reuse();
      if (!KOPF3()) return reject(UnknownWortartKopf);
      if (!WortartTemplate()) return reject(UnknownWortartKopf);
      while (!KOPF3())
        if (!next($Term14)) return reject(UnknownWortartKopf);
      if (!RestOfLine()) return reject(UnknownWortartKopf);
      return accept(UnknownWortartKopf);
    }
  
  //=====================================================================
  //  WortartTemplate = LT "Wortart" SEP TemplateAttr SEP "Deutsch" RT
  //    {WortartTemplate} ;
  //=====================================================================
  private boolean WortartTemplate()
    {
      if (saved(WortartTemplate)) return reuse();
      if (!LT()) return reject(WortartTemplate);
      if (!next("Wortart",$Term12)) return reject(WortartTemplate);
      if (!SEP()) return reject(WortartTemplate);
      TemplateAttr();
      if (!SEP()) return reject(WortartTemplate);
      if (!next("Deutsch",$Term46)) return reject(WortartTemplate);
      if (!RT()) return reject(WortartTemplate);
      sem.WortartTemplate();
      return accept(WortartTemplate);
    }
  
  //=====================================================================
  //  SubstantivKopf = KOPF3 SubstantivTemplate SubstantivAttributes
  //    KOPF3 RestOfLine ;
  //=====================================================================
  private boolean SubstantivKopf()
    {
      if (saved(SubstantivKopf)) return reuse();
      if (!KOPF3()) return reject(SubstantivKopf);
      if (!SubstantivTemplate()) return reject(SubstantivKopf);
      if (!SubstantivAttributes()) return reject(SubstantivKopf);
      if (!KOPF3()) return reject(SubstantivKopf);
      if (!RestOfLine()) return reject(SubstantivKopf);
      return accept(SubstantivKopf);
    }
  
  //=====================================================================
  //  SubstantivTemplate = LT "Wortart" SEP "Substantiv" SEP "Deutsch" RT
  //    {createSubstantiv} ;
  //=====================================================================
  private boolean SubstantivTemplate()
    {
      if (saved(SubstantivTemplate)) return reuse();
      if (!LT()) return reject(SubstantivTemplate);
      if (!next("Wortart",$Term12)) return reject(SubstantivTemplate);
      if (!SEP()) return reject(SubstantivTemplate);
      if (!next("Substantiv",$Term5)) return reject(SubstantivTemplate);
      if (!SEP()) return reject(SubstantivTemplate);
      if (!next("Deutsch",$Term46)) return reject(SubstantivTemplate);
      if (!RT()) return reject(SubstantivTemplate);
      sem.createSubstantiv();
      return accept(SubstantivTemplate);
    }
  
  //=====================================================================
  //  SubstantivAttributes = (","? Space SubstantivAttribute)+
  //    ~{SubstantivAttributes_0_fail} / _++ KOPF3 ;
  //=====================================================================
  private boolean SubstantivAttributes()
    {
      if (saved(SubstantivAttributes)) return reuse();
      if (SubstantivAttributes_0()) return accept(SubstantivAttributes);
      else sem.SubstantivAttributes_0_fail();
      if (SubstantivAttributes_1()) return accept(SubstantivAttributes);
      return reject(SubstantivAttributes);
    }
  
  //-------------------------------------------------------------------
  //  SubstantivAttributes_0 = (","? Space SubstantivAttribute)+
  //-------------------------------------------------------------------
  private boolean SubstantivAttributes_0()
    {
      if (savedInner(SubstantivAttributes_0)) return reuseInner();
      if (!SubstantivAttributes_2()) return rejectInner(SubstantivAttributes_0);
      while (SubstantivAttributes_2());
      return acceptInner(SubstantivAttributes_0);
    }
  
  //-------------------------------------------------------------------
  //  SubstantivAttributes_1 = _++ KOPF3
  //-------------------------------------------------------------------
  private boolean SubstantivAttributes_1()
    {
      if (savedInner(SubstantivAttributes_1)) return reuseInner();
      if (KOPF3()) return rejectInner(SubstantivAttributes_1);
      do if (!next($Term61)) return rejectInner(SubstantivAttributes_1);
        while (!KOPF3());
      return acceptInner(SubstantivAttributes_1);
    }
  
  //-------------------------------------------------------------------
  //  SubstantivAttributes_2 = ","? Space SubstantivAttribute
  //-------------------------------------------------------------------
  private boolean SubstantivAttributes_2()
    {
      if (savedInner(SubstantivAttributes_2)) return reuseInner();
      next(',',$Term63);
      Space();
      if (!SubstantivAttribute()) return rejectInner(SubstantivAttributes_2);
      return acceptInner(SubstantivAttributes_2);
    }
  
  //=====================================================================
  //  SubstantivAttribute = Gender {substantivGender} / WortartTemplate
  //    {substantivWortart} / "''adjektivische Deklination" ","? "''"
  //    {substantivAdjDeklination} ;
  //=====================================================================
  private boolean SubstantivAttribute()
    {
      if (saved(SubstantivAttribute)) return reuse();
      if (Gender())
      { sem.substantivGender(); return accept(SubstantivAttribute); }
      if (WortartTemplate())
      { sem.substantivWortart(); return accept(SubstantivAttribute); }
      if (SubstantivAttribute_0())
      { sem.substantivAdjDeklination(); return accept(SubstantivAttribute); }
      return reject(SubstantivAttribute);
    }
  
  //-------------------------------------------------------------------
  //  SubstantivAttribute_0 = "''adjektivische Deklination" ","? "''"
  //-------------------------------------------------------------------
  private boolean SubstantivAttribute_0()
    {
      if (savedInner(SubstantivAttribute_0)) return reuseInner();
      if (!next("''adjektivische Deklination",$Term62)) return rejectInner(SubstantivAttribute_0);
      next(',',$Term63);
      if (!next("''",$Term47)) return rejectInner(SubstantivAttribute_0);
      return acceptInner(SubstantivAttribute_0);
    }
  
  //=====================================================================
  //  FlexionTable = FlexionTableKopf FlexionForm+ RT RestOfLine ;
  //=====================================================================
  private boolean FlexionTable()
    {
      if (saved(FlexionTable)) return reuse();
      if (!FlexionTableKopf()) return reject(FlexionTable);
      if (!FlexionForm()) return reject(FlexionTable);
      while (FlexionForm());
      if (!RT()) return reject(FlexionTable);
      if (!RestOfLine()) return reject(FlexionTable);
      return accept(FlexionTable);
    }
  
  //=====================================================================
  //  FlexionTableKopf = LT "Deutsch Substantiv Übersicht" Space
  //    RestOfLine ;
  //=====================================================================
  private boolean FlexionTableKopf()
    {
      if (saved(FlexionTableKopf)) return reuse();
      if (!LT()) return reject(FlexionTableKopf);
      if (!next("Deutsch Substantiv \u00dcbersicht",$Term56)) return reject(FlexionTableKopf);
      Space();
      if (!RestOfLine()) return reject(FlexionTableKopf);
      return accept(FlexionTableKopf);
    }
  
  //=====================================================================
  //  FlexionForm = SEP (NomSg / NomPl / GenSg / GenPl / DatSg / DatPl /
  //    AkkSg / AkkPl / BadLine) ;
  //=====================================================================
  private boolean FlexionForm()
    {
      if (saved(FlexionForm)) return reuse();
      if (!SEP()) return reject(FlexionForm);
      if (!NomSg()
       && !NomPl()
       && !GenSg()
       && !GenPl()
       && !DatSg()
       && !DatPl()
       && !AkkSg()
       && !AkkPl()
       && !BadLine()
         ) return reject(FlexionForm);
      return accept(FlexionForm);
    }
  
  //=====================================================================
  //  NomSg = "Nominativ Singular" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addNomSg} ;
  //=====================================================================
  private boolean NomSg()
    {
      if (saved(NomSg)) return reuse();
      if (!next("Nominativ Singular",$Term24)) return reject(NomSg);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(NomSg);
      FlexionVariantList();
      if (!RestOfLine()) return reject(NomSg);
      sem.addNomSg();
      return accept(NomSg);
    }
  
  //=====================================================================
  //  NomPl = "Nominativ Plural" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addNomPl} ;
  //=====================================================================
  private boolean NomPl()
    {
      if (saved(NomPl)) return reuse();
      if (!next("Nominativ Plural",$Term2)) return reject(NomPl);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(NomPl);
      FlexionVariantList();
      if (!RestOfLine()) return reject(NomPl);
      sem.addNomPl();
      return accept(NomPl);
    }
  
  //=====================================================================
  //  GenSg = "Genitiv Singular" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addGenSg} ;
  //=====================================================================
  private boolean GenSg()
    {
      if (saved(GenSg)) return reuse();
      if (!next("Genitiv Singular",$Term33)) return reject(GenSg);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(GenSg);
      FlexionVariantList();
      if (!RestOfLine()) return reject(GenSg);
      sem.addGenSg();
      return accept(GenSg);
    }
  
  //=====================================================================
  //  GenPl = "Genitiv Plural" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addGenPl} ;
  //=====================================================================
  private boolean GenPl()
    {
      if (saved(GenPl)) return reuse();
      if (!next("Genitiv Plural",$Term52)) return reject(GenPl);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(GenPl);
      FlexionVariantList();
      if (!RestOfLine()) return reject(GenPl);
      sem.addGenPl();
      return accept(GenPl);
    }
  
  //=====================================================================
  //  DatSg = "Dativ Singular" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addDatSg} ;
  //=====================================================================
  private boolean DatSg()
    {
      if (saved(DatSg)) return reuse();
      if (!next("Dativ Singular",$Term42)) return reject(DatSg);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(DatSg);
      FlexionVariantList();
      if (!RestOfLine()) return reject(DatSg);
      sem.addDatSg();
      return accept(DatSg);
    }
  
  //=====================================================================
  //  DatPl = "Dativ Plural" Space OptDigit Space "=" FlexionVariantList
  //    RestOfLine {addDatPl} ;
  //=====================================================================
  private boolean DatPl()
    {
      if (saved(DatPl)) return reuse();
      if (!next("Dativ Plural",$Term58)) return reject(DatPl);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(DatPl);
      FlexionVariantList();
      if (!RestOfLine()) return reject(DatPl);
      sem.addDatPl();
      return accept(DatPl);
    }
  
  //=====================================================================
  //  AkkSg = "Akkusativ Singular" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addAkkSg} ;
  //=====================================================================
  private boolean AkkSg()
    {
      if (saved(AkkSg)) return reuse();
      if (!next("Akkusativ Singular",$Term31)) return reject(AkkSg);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(AkkSg);
      FlexionVariantList();
      if (!RestOfLine()) return reject(AkkSg);
      sem.addAkkSg();
      return accept(AkkSg);
    }
  
  //=====================================================================
  //  AkkPl = "Akkusativ Plural" Space OptDigit Space "="
  //    FlexionVariantList RestOfLine {addAkkPl} ;
  //=====================================================================
  private boolean AkkPl()
    {
      if (saved(AkkPl)) return reuse();
      if (!next("Akkusativ Plural",$Term38)) return reject(AkkPl);
      Space();
      OptDigit();
      Space();
      if (!next('=',$Term51)) return reject(AkkPl);
      FlexionVariantList();
      if (!RestOfLine()) return reject(AkkPl);
      sem.addAkkPl();
      return accept(AkkPl);
    }
  
  //=====================================================================
  //  FlexionVariantList = Space Phrase (BR Phrase)*
  //    {FlexionVariantList_0} / Space "\u2014" Space
  //    {FlexionVariantList_1} / (!EOL _)* ;
  //=====================================================================
  private boolean FlexionVariantList()
    {
      if (saved(FlexionVariantList)) return reuse();
      if (FlexionVariantList_0())
      { sem.FlexionVariantList_0(); return accept(FlexionVariantList); }
      if (FlexionVariantList_1())
      { sem.FlexionVariantList_1(); return accept(FlexionVariantList); }
      if (FlexionVariantList_2()) return accept(FlexionVariantList);
      return reject(FlexionVariantList);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_0 = Space Phrase (BR Phrase)*
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_0()
    {
      if (savedInner(FlexionVariantList_0)) return reuseInner();
      Space();
      if (!Phrase()) return rejectInner(FlexionVariantList_0);
      while (FlexionVariantList_3());
      return acceptInner(FlexionVariantList_0);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_1 = Space "\u2014" Space
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_1()
    {
      if (savedInner(FlexionVariantList_1)) return reuseInner();
      Space();
      if (!next('\u2014',$Term55)) return rejectInner(FlexionVariantList_1);
      Space();
      return acceptInner(FlexionVariantList_1);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_2 = (!EOL _)*
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_2()
    {
      if (savedInner(FlexionVariantList_2)) return reuseInner();
      while (FlexionVariantList_4());
      return acceptInner(FlexionVariantList_2);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_3 = BR Phrase
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_3()
    {
      if (savedInner(FlexionVariantList_3)) return reuseInner();
      if (!BR()) return rejectInner(FlexionVariantList_3);
      if (!Phrase()) return rejectInner(FlexionVariantList_3);
      return acceptInner(FlexionVariantList_3);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_4 = !EOL _
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_4()
    {
      if (savedInner(FlexionVariantList_4)) return reuseInner();
      if (!FlexionVariantList_5()) return rejectInner(FlexionVariantList_4);
      if (!next($Term14)) return rejectInner(FlexionVariantList_4);
      return acceptInner(FlexionVariantList_4);
    }
  
  //-------------------------------------------------------------------
  //  FlexionVariantList_5 = !EOL
  //-------------------------------------------------------------------
  private boolean FlexionVariantList_5()
    {
      if (savedInner(FlexionVariantList_5)) return reusePred();
      if (EOL()) return rejectNot(FlexionVariantList_5);
      return acceptNot(FlexionVariantList_5);
    }
  
  //=====================================================================
  //  Gender = LT GenderTemplateArgument RT Space {Gender} ;
  //=====================================================================
  private boolean Gender()
    {
      if (saved(Gender)) return reuse();
      if (!LT()) return reject(Gender);
      if (!GenderTemplateArgument()) return reject(Gender);
      if (!RT()) return reject(Gender);
      Space();
      sem.Gender();
      return accept(Gender);
    }
  
  //=====================================================================
  //  GenderTemplateArgument = "mf" / "f" ("m" / "n") / "n" ("m" / "f") /
  //    "m" / "f" / "n" / "u" ;
  //=====================================================================
  private boolean GenderTemplateArgument()
    {
      if (saved(GenderTemplateArgument)) return reuse();
      if (next("mf",$Term43)) return accept(GenderTemplateArgument);
      if (GenderTemplateArgument_0()) return accept(GenderTemplateArgument);
      if (GenderTemplateArgument_1()) return accept(GenderTemplateArgument);
      if (next('m',$Term40)) return accept(GenderTemplateArgument);
      if (next('f',$Term30)) return accept(GenderTemplateArgument);
      if (next('n',$Term48)) return accept(GenderTemplateArgument);
      if (next('u',$Term9)) return accept(GenderTemplateArgument);
      return reject(GenderTemplateArgument);
    }
  
  //-------------------------------------------------------------------
  //  GenderTemplateArgument_0 = "f" ("m" / "n")
  //-------------------------------------------------------------------
  private boolean GenderTemplateArgument_0()
    {
      if (savedInner(GenderTemplateArgument_0)) return reuseInner();
      if (!next('f',$Term30)) return rejectInner(GenderTemplateArgument_0);
      if (!next('m',$Term40)
       && !next('n',$Term48)
         ) return rejectInner(GenderTemplateArgument_0);
      return acceptInner(GenderTemplateArgument_0);
    }
  
  //-------------------------------------------------------------------
  //  GenderTemplateArgument_1 = "n" ("m" / "f")
  //-------------------------------------------------------------------
  private boolean GenderTemplateArgument_1()
    {
      if (savedInner(GenderTemplateArgument_1)) return reuseInner();
      if (!next('n',$Term48)) return rejectInner(GenderTemplateArgument_1);
      if (!next('m',$Term40)
       && !next('f',$Term30)
         ) return rejectInner(GenderTemplateArgument_1);
      return acceptInner(GenderTemplateArgument_1);
    }
  
  //=====================================================================
  //  MiddleSection = (!TranslationsKopf (FlexionTable /
  //    MeaningsTextbaustein / Line))* ;
  //=====================================================================
  private boolean MiddleSection()
    {
      if (saved(MiddleSection)) return reuse();
      while (MiddleSection_0());
      return accept(MiddleSection);
    }
  
  //-------------------------------------------------------------------
  //  MiddleSection_0 = !TranslationsKopf (FlexionTable /
  //    MeaningsTextbaustein / Line)
  //-------------------------------------------------------------------
  private boolean MiddleSection_0()
    {
      if (savedInner(MiddleSection_0)) return reuseInner();
      if (!MiddleSection_1()) return rejectInner(MiddleSection_0);
      if (!FlexionTable()
       && !MeaningsTextbaustein()
       && !Line()
         ) return rejectInner(MiddleSection_0);
      return acceptInner(MiddleSection_0);
    }
  
  //-------------------------------------------------------------------
  //  MiddleSection_1 = !TranslationsKopf
  //-------------------------------------------------------------------
  private boolean MiddleSection_1()
    {
      if (savedInner(MiddleSection_1)) return reusePred();
      if (TranslationsKopf()) return rejectNot(MiddleSection_1);
      return acceptNot(MiddleSection_1);
    }
  
  //=====================================================================
  //  MeaningsTextbaustein = MeaningsKopf MeaningList ;
  //=====================================================================
  private boolean MeaningsTextbaustein()
    {
      if (saved(MeaningsTextbaustein)) return reuse();
      if (!MeaningsKopf()) return reject(MeaningsTextbaustein);
      MeaningList();
      return accept(MeaningsTextbaustein);
    }
  
  //=====================================================================
  //  MeaningsKopf = LT "Bedeutungen" RT RestOfLine ;
  //=====================================================================
  private boolean MeaningsKopf()
    {
      if (saved(MeaningsKopf)) return reuse();
      if (!LT()) return reject(MeaningsKopf);
      if (!next("Bedeutungen",$Term49)) return reject(MeaningsKopf);
      if (!RT()) return reject(MeaningsKopf);
      if (!RestOfLine()) return reject(MeaningsKopf);
      return accept(MeaningsKopf);
    }
  
  //=====================================================================
  //  MeaningList = (!TextbausteinEnd (Meaning / Line))* ;
  //=====================================================================
  private boolean MeaningList()
    {
      if (saved(MeaningList)) return reuse();
      while (MeaningList_0());
      return accept(MeaningList);
    }
  
  //-------------------------------------------------------------------
  //  MeaningList_0 = !TextbausteinEnd (Meaning / Line)
  //-------------------------------------------------------------------
  private boolean MeaningList_0()
    {
      if (savedInner(MeaningList_0)) return reuseInner();
      if (!MeaningList_1()) return rejectInner(MeaningList_0);
      if (!Meaning()
       && !Line()
         ) return rejectInner(MeaningList_0);
      return acceptInner(MeaningList_0);
    }
  
  //-------------------------------------------------------------------
  //  MeaningList_1 = !TextbausteinEnd
  //-------------------------------------------------------------------
  private boolean MeaningList_1()
    {
      if (savedInner(MeaningList_1)) return reusePred();
      if (TextbausteinEnd()) return rejectNot(MeaningList_1);
      return acceptNot(MeaningList_1);
    }
  
  //=====================================================================
  //  Meaning = MeaningLvl RichTextComponent++ EOL {Meaning} ;
  //=====================================================================
  private boolean Meaning()
    {
      if (saved(Meaning)) return reuse();
      if (!MeaningLvl()) return reject(Meaning);
      if (EOL()) return reject(Meaning);
      do if (!RichTextComponent()) return reject(Meaning);
        while (!EOL());
      sem.Meaning();
      return accept(Meaning);
    }
  
  //=====================================================================
  //  MeaningLvl = ":"+ (ItemNo / "*") ;
  //=====================================================================
  private boolean MeaningLvl()
    {
      if (saved(MeaningLvl)) return reuse();
      if (!next(':',$Term26)) return reject(MeaningLvl);
      while (next(':',$Term26));
      if (!ItemNo()
       && !next('*',$Term21)
         ) return reject(MeaningLvl);
      return accept(MeaningLvl);
    }
  
  //=====================================================================
  //  TranslationsSection = TranslationsKopf (!TranslationsTableKopf
  //    Line)* TranslationsTable (!KopfStart Line)* ;
  //=====================================================================
  private boolean TranslationsSection()
    {
      if (saved(TranslationsSection)) return reuse();
      if (!TranslationsKopf()) return reject(TranslationsSection);
      while (TranslationsSection_0());
      if (!TranslationsTable()) return reject(TranslationsSection);
      while (TranslationsSection_1());
      return accept(TranslationsSection);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsSection_0 = !TranslationsTableKopf Line
  //-------------------------------------------------------------------
  private boolean TranslationsSection_0()
    {
      if (savedInner(TranslationsSection_0)) return reuseInner();
      if (!TranslationsSection_2()) return rejectInner(TranslationsSection_0);
      if (!Line()) return rejectInner(TranslationsSection_0);
      return acceptInner(TranslationsSection_0);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsSection_1 = !KopfStart Line
  //-------------------------------------------------------------------
  private boolean TranslationsSection_1()
    {
      if (savedInner(TranslationsSection_1)) return reuseInner();
      if (!TranslationsSection_3()) return rejectInner(TranslationsSection_1);
      if (!Line()) return rejectInner(TranslationsSection_1);
      return acceptInner(TranslationsSection_1);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsSection_2 = !TranslationsTableKopf
  //-------------------------------------------------------------------
  private boolean TranslationsSection_2()
    {
      if (savedInner(TranslationsSection_2)) return reusePred();
      if (TranslationsTableKopf()) return rejectNot(TranslationsSection_2);
      return acceptNot(TranslationsSection_2);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsSection_3 = !KopfStart
  //-------------------------------------------------------------------
  private boolean TranslationsSection_3()
    {
      if (savedInner(TranslationsSection_3)) return reusePred();
      if (KopfStart()) return rejectNot(TranslationsSection_3);
      return acceptNot(TranslationsSection_3);
    }
  
  //=====================================================================
  //  TranslationsKopf = KOPF4 "Übersetzungen" Space KOPF4 RestOfLine ;
  //=====================================================================
  private boolean TranslationsKopf()
    {
      if (saved(TranslationsKopf)) return reuse();
      if (!KOPF4()) return reject(TranslationsKopf);
      if (!next("\u00dcbersetzungen",$Term57)) return reject(TranslationsKopf);
      Space();
      if (!KOPF4()) return reject(TranslationsKopf);
      if (!RestOfLine()) return reject(TranslationsKopf);
      return accept(TranslationsKopf);
    }
  
  //=====================================================================
  //  TranslationsTable = TranslationsTableKopf (LangTranslations /
  //    DialectTable / !RT Line)*+ RT RestOfLine ;
  //=====================================================================
  private boolean TranslationsTable()
    {
      if (saved(TranslationsTable)) return reuse();
      if (!TranslationsTableKopf()) return reject(TranslationsTable);
      while (!RT())
        if (!TranslationsTable_0()) return reject(TranslationsTable);
      if (!RestOfLine()) return reject(TranslationsTable);
      return accept(TranslationsTable);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsTable_0 = LangTranslations / DialectTable / !RT Line
  //-------------------------------------------------------------------
  private boolean TranslationsTable_0()
    {
      if (savedInner(TranslationsTable_0)) return reuseInner();
      if (LangTranslations()) return acceptInner(TranslationsTable_0);
      if (DialectTable()) return acceptInner(TranslationsTable_0);
      if (TranslationsTable_1()) return acceptInner(TranslationsTable_0);
      return rejectInner(TranslationsTable_0);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsTable_1 = !RT Line
  //-------------------------------------------------------------------
  private boolean TranslationsTable_1()
    {
      if (savedInner(TranslationsTable_1)) return reuseInner();
      if (!TranslationsTable_2()) return rejectInner(TranslationsTable_1);
      if (!Line()) return rejectInner(TranslationsTable_1);
      return acceptInner(TranslationsTable_1);
    }
  
  //-------------------------------------------------------------------
  //  TranslationsTable_2 = !RT
  //-------------------------------------------------------------------
  private boolean TranslationsTable_2()
    {
      if (savedInner(TranslationsTable_2)) return reusePred();
      if (RT()) return rejectNot(TranslationsTable_2);
      return acceptNot(TranslationsTable_2);
    }
  
  //=====================================================================
  //  TranslationsTableKopf = LT "Ü-Tabelle" Line ;
  //=====================================================================
  private boolean TranslationsTableKopf()
    {
      if (saved(TranslationsTableKopf)) return reuse();
      if (!LT()) return reject(TranslationsTableKopf);
      if (!next("\u00dc-Tabelle",$Term1)) return reject(TranslationsTableKopf);
      if (!Line()) return reject(TranslationsTableKopf);
      return accept(TranslationsTableKopf);
    }
  
  //=====================================================================
  //  LangTranslations = LangLvl Lang ":" Space TranslationMeaning*
  //    RestOfLine {addTranslationsForLanguage} ;
  //=====================================================================
  private boolean LangTranslations()
    {
      if (saved(LangTranslations)) return reuse();
      if (!LangLvl()) return reject(LangTranslations);
      if (!Lang()) return reject(LangTranslations);
      if (!next(':',$Term26)) return reject(LangTranslations);
      Space();
      while (TranslationMeaning());
      if (!RestOfLine()) return reject(LangTranslations);
      sem.addTranslationsForLanguage();
      return accept(LangTranslations);
    }
  
  //=====================================================================
  //  LangLvl = "*"+ ;
  //=====================================================================
  private boolean LangLvl()
    {
      if (saved(LangLvl)) return reuse();
      if (!next('*',$Term21)) return reject(LangLvl);
      while (next('*',$Term21));
      return accept(LangLvl);
    }
  
  //=====================================================================
  //  Lang = LT Word RT {Lang} ;
  //=====================================================================
  private boolean Lang()
    {
      if (saved(Lang)) return reuse();
      if (!LT()) return reject(Lang);
      if (!Word()) return reject(Lang);
      if (!RT()) return reject(Lang);
      sem.Lang();
      return accept(Lang);
    }
  
  //=====================================================================
  //  TranslationMeaning = ItemNo Translation+ {TranslationMeaning} ;
  //=====================================================================
  private boolean TranslationMeaning()
    {
      if (saved(TranslationMeaning)) return reuse();
      if (!ItemNo()) return reject(TranslationMeaning);
      if (!Translation()) return reject(TranslationMeaning);
      while (Translation());
      sem.TranslationMeaning();
      return accept(TranslationMeaning);
    }
  
  //=====================================================================
  //  Translation = TranslationDetails (UeTemplate / UetTemplate) Gender?
  //    TranslationDetails (COMMA / SEMICOLON)? Space {Translation} ;
  //=====================================================================
  private boolean Translation()
    {
      if (saved(Translation)) return reuse();
      TranslationDetails();
      if (!UeTemplate()
       && !UetTemplate()
         ) return reject(Translation);
      Gender();
      TranslationDetails();
      Translation_0();
      Space();
      sem.Translation();
      return accept(Translation);
    }
  
  //-------------------------------------------------------------------
  //  Translation_0 = COMMA / SEMICOLON
  //-------------------------------------------------------------------
  private boolean Translation_0()
    {
      if (savedInner(Translation_0)) return reuseInner();
      if (COMMA()) return acceptInner(Translation_0);
      if (SEMICOLON()) return acceptInner(Translation_0);
      return rejectInner(Translation_0);
    }
  
  //=====================================================================
  //  TranslationDetails = (CursiveText / Link / !(ItemNo / UeTemplate /
  //    UetTemplate / COMMA / SEMICOLON / EOL) _)* (COMMA / SEMICOLON)?
  //    ;
  //=====================================================================
  private boolean TranslationDetails()
    {
      if (saved(TranslationDetails)) return reuse();
      while (TranslationDetails_0());
      Translation_0();
      return accept(TranslationDetails);
    }
  
  //-------------------------------------------------------------------
  //  TranslationDetails_0 = CursiveText / Link / !(ItemNo / UeTemplate
  //    / UetTemplate / COMMA / SEMICOLON / EOL) _
  //-------------------------------------------------------------------
  private boolean TranslationDetails_0()
    {
      if (savedInner(TranslationDetails_0)) return reuseInner();
      if (CursiveText()) return acceptInner(TranslationDetails_0);
      if (Link()) return acceptInner(TranslationDetails_0);
      if (TranslationDetails_1()) return acceptInner(TranslationDetails_0);
      return rejectInner(TranslationDetails_0);
    }
  
  //-------------------------------------------------------------------
  //  TranslationDetails_1 = !(ItemNo / UeTemplate / UetTemplate /
  //    COMMA / SEMICOLON / EOL) _
  //-------------------------------------------------------------------
  private boolean TranslationDetails_1()
    {
      if (savedInner(TranslationDetails_1)) return reuseInner();
      if (!TranslationDetails_2()) return rejectInner(TranslationDetails_1);
      if (!next($Term14)) return rejectInner(TranslationDetails_1);
      return acceptInner(TranslationDetails_1);
    }
  
  //-------------------------------------------------------------------
  //  TranslationDetails_2 = !(ItemNo / UeTemplate / UetTemplate /
  //    COMMA / SEMICOLON / EOL)
  //-------------------------------------------------------------------
  private boolean TranslationDetails_2()
    {
      if (savedInner(TranslationDetails_2)) return reusePred();
      if (TranslationDetails_3()) return rejectNot(TranslationDetails_2);
      return acceptNot(TranslationDetails_2);
    }
  
  //-------------------------------------------------------------------
  //  TranslationDetails_3 = ItemNo / UeTemplate / UetTemplate / COMMA
  //    / SEMICOLON / EOL
  //-------------------------------------------------------------------
  private boolean TranslationDetails_3()
    {
      if (savedInner(TranslationDetails_3)) return reuseInner();
      if (ItemNo()) return acceptInner(TranslationDetails_3);
      if (UeTemplate()) return acceptInner(TranslationDetails_3);
      if (UetTemplate()) return acceptInner(TranslationDetails_3);
      if (COMMA()) return acceptInner(TranslationDetails_3);
      if (SEMICOLON()) return acceptInner(TranslationDetails_3);
      if (EOL()) return acceptInner(TranslationDetails_3);
      return rejectInner(TranslationDetails_3);
    }
  
  //=====================================================================
  //  UeTemplate = LT ("Ü" / "Ü?") SEP TemplateAttr SEP TemplateAttr (SEP
  //    TemplateAttr)? (SEP TemplateAttr)? RT Space {UeTemplate} ;
  //=====================================================================
  private boolean UeTemplate()
    {
      if (saved(UeTemplate)) return reuse();
      if (!LT()) return reject(UeTemplate);
      if (!next('\u00dc',$Term19)
       && !next("\u00dc?",$Term27)
         ) return reject(UeTemplate);
      if (!SEP()) return reject(UeTemplate);
      TemplateAttr();
      if (!SEP()) return reject(UeTemplate);
      TemplateAttr();
      UeTemplate_0();
      UeTemplate_0();
      if (!RT()) return reject(UeTemplate);
      Space();
      sem.UeTemplate();
      return accept(UeTemplate);
    }
  
  //-------------------------------------------------------------------
  //  UeTemplate_0 = SEP TemplateAttr
  //-------------------------------------------------------------------
  private boolean UeTemplate_0()
    {
      if (savedInner(UeTemplate_0)) return reuseInner();
      if (!SEP()) return rejectInner(UeTemplate_0);
      TemplateAttr();
      return acceptInner(UeTemplate_0);
    }
  
  //=====================================================================
  //  UetTemplate = LT ("Üt" / "Üt?") SEP TemplateAttr SEP TemplateAttr
  //    SEP TemplateAttr (SEP TemplateAttr)? (SEP TemplateAttr)? RT Space
  //    {UetTemplate} ;
  //=====================================================================
  private boolean UetTemplate()
    {
      if (saved(UetTemplate)) return reuse();
      if (!LT()) return reject(UetTemplate);
      if (!next("\u00dct",$Term54)
       && !next("\u00dct?",$Term16)
         ) return reject(UetTemplate);
      if (!SEP()) return reject(UetTemplate);
      TemplateAttr();
      if (!SEP()) return reject(UetTemplate);
      TemplateAttr();
      if (!SEP()) return reject(UetTemplate);
      TemplateAttr();
      UeTemplate_0();
      UeTemplate_0();
      if (!RT()) return reject(UetTemplate);
      Space();
      sem.UetTemplate();
      return accept(UetTemplate);
    }
  
  //=====================================================================
  //  DialectTable = "|Dialekttabelle=" RestOfLine (!RT Line)* ;
  //=====================================================================
  private boolean DialectTable()
    {
      if (saved(DialectTable)) return reuse();
      if (!next("|Dialekttabelle=",$Term25)) return reject(DialectTable);
      if (!RestOfLine()) return reject(DialectTable);
      while (TranslationsTable_1());
      return accept(DialectTable);
    }
  
  //=====================================================================
  //  KOPF2 = "==" Space ;
  //=====================================================================
  private boolean KOPF2()
    {
      if (saved(KOPF2)) return reuse();
      if (!next("==",$Term6)) return reject(KOPF2);
      Space();
      return accept(KOPF2);
    }
  
  //=====================================================================
  //  KOPF3 = "===" Space ;
  //=====================================================================
  private boolean KOPF3()
    {
      if (saved(KOPF3)) return reuse();
      if (!next("===",$Term10)) return reject(KOPF3);
      Space();
      return accept(KOPF3);
    }
  
  //=====================================================================
  //  KOPF4 = "====" Space ;
  //=====================================================================
  private boolean KOPF4()
    {
      if (saved(KOPF4)) return reuse();
      if (!next("====",$Term44)) return reject(KOPF4);
      Space();
      return accept(KOPF4);
    }
  
  //=====================================================================
  //  KopfStart = "==" ;
  //=====================================================================
  private boolean KopfStart()
    {
      if (saved(KopfStart)) return reuse();
      if (!next("==",$Term6)) return reject(KopfStart);
      return accept(KopfStart);
    }
  
  //=====================================================================
  //  SEP = "|" Space ;
  //=====================================================================
  private boolean SEP()
    {
      if (saved(SEP)) return reuse();
      if (!next('|',$Term3)) return reject(SEP);
      Space();
      return accept(SEP);
    }
  
  //=====================================================================
  //  TextbausteinEnd = LT / KopfStart / EOF ;
  //=====================================================================
  private boolean TextbausteinEnd()
    {
      if (saved(TextbausteinEnd)) return reuse();
      if (LT()) return accept(TextbausteinEnd);
      if (KopfStart()) return accept(TextbausteinEnd);
      if (EOF()) return accept(TextbausteinEnd);
      return reject(TextbausteinEnd);
    }
  
  //=====================================================================
  //  RichTextComponent = Link {RichTextComponent_0} / CursiveText
  //    {RichTextComponent_1} / Template {RichTextComponent_2} / !EOL _
  //    {RichTextComponent_3} ;
  //=====================================================================
  private boolean RichTextComponent()
    {
      if (saved(RichTextComponent)) return reuse();
      if (Link())
      { sem.RichTextComponent_0(); return accept(RichTextComponent); }
      if (CursiveText())
      { sem.RichTextComponent_1(); return accept(RichTextComponent); }
      if (Template())
      { sem.RichTextComponent_2(); return accept(RichTextComponent); }
      if (FlexionVariantList_4())
      { sem.RichTextComponent_3(); return accept(RichTextComponent); }
      return reject(RichTextComponent);
    }
  
  //=====================================================================
  //  LL = "[[" ;
  //=====================================================================
  private boolean LL()
    {
      if (saved(LL)) return reuse();
      if (!next("[[",$Term41)) return reject(LL);
      return accept(LL);
    }
  
  //=====================================================================
  //  RL = "]]" ;
  //=====================================================================
  private boolean RL()
    {
      if (saved(RL)) return reuse();
      if (!next("]]",$Term35)) return reject(RL);
      return accept(RL);
    }
  
  //=====================================================================
  //  Link = LL LinkAttr (SEP LinkAttr)? RL {Link} ;
  //=====================================================================
  private boolean Link()
    {
      if (saved(Link)) return reuse();
      if (!LL()) return reject(Link);
      if (!LinkAttr()) return reject(Link);
      Link_0();
      if (!RL()) return reject(Link);
      sem.Link();
      return accept(Link);
    }
  
  //-------------------------------------------------------------------
  //  Link_0 = SEP LinkAttr
  //-------------------------------------------------------------------
  private boolean Link_0()
    {
      if (savedInner(Link_0)) return reuseInner();
      if (!SEP()) return rejectInner(Link_0);
      if (!LinkAttr()) return rejectInner(Link_0);
      return acceptInner(Link_0);
    }
  
  //=====================================================================
  //  LinkAttr = (!(SEP / RL) _)+ ;
  //=====================================================================
  private boolean LinkAttr()
    {
      if (saved(LinkAttr)) return reuse();
      if (!LinkAttr_0()) return reject(LinkAttr);
      while (LinkAttr_0());
      return accept(LinkAttr);
    }
  
  //-------------------------------------------------------------------
  //  LinkAttr_0 = !(SEP / RL) _
  //-------------------------------------------------------------------
  private boolean LinkAttr_0()
    {
      if (savedInner(LinkAttr_0)) return reuseInner();
      if (!LinkAttr_1()) return rejectInner(LinkAttr_0);
      if (!next($Term14)) return rejectInner(LinkAttr_0);
      return acceptInner(LinkAttr_0);
    }
  
  //-------------------------------------------------------------------
  //  LinkAttr_1 = !(SEP / RL)
  //-------------------------------------------------------------------
  private boolean LinkAttr_1()
    {
      if (savedInner(LinkAttr_1)) return reusePred();
      if (LinkAttr_2()) return rejectNot(LinkAttr_1);
      return acceptNot(LinkAttr_1);
    }
  
  //-------------------------------------------------------------------
  //  LinkAttr_2 = SEP / RL
  //-------------------------------------------------------------------
  private boolean LinkAttr_2()
    {
      if (savedInner(LinkAttr_2)) return reuseInner();
      if (SEP()) return acceptInner(LinkAttr_2);
      if (RL()) return acceptInner(LinkAttr_2);
      return rejectInner(LinkAttr_2);
    }
  
  //=====================================================================
  //  CursiveText = "''" RichTextComponent*+ "''" Space {CursiveText} ;
  //=====================================================================
  private boolean CursiveText()
    {
      if (saved(CursiveText)) return reuse();
      if (!next("''",$Term47)) return reject(CursiveText);
      while (!next("''",$Term13))
        if (!RichTextComponent()) return reject(CursiveText);
      Space();
      sem.CursiveText();
      return accept(CursiveText);
    }
  
  //=====================================================================
  //  LT = "{{" Space ;
  //=====================================================================
  private boolean LT()
    {
      if (saved(LT)) return reuse();
      if (!next("{{",$Term23)) return reject(LT);
      Space();
      return accept(LT);
    }
  
  //=====================================================================
  //  RT = "}}" Space ;
  //=====================================================================
  private boolean RT()
    {
      if (saved(RT)) return reuse();
      if (!next("}}",$Term15)) return reject(RT);
      Space();
      return accept(RT);
    }
  
  //=====================================================================
  //  Template = LT TemplateAttr (SEP TemplateAttr)* RT {Template} ;
  //=====================================================================
  private boolean Template()
    {
      if (saved(Template)) return reuse();
      if (!LT()) return reject(Template);
      TemplateAttr();
      while (UeTemplate_0());
      if (!RT()) return reject(Template);
      sem.Template();
      return accept(Template);
    }
  
  //=====================================================================
  //  TemplateAttr = (!(SEP / RT) RichTextComponent)* {TemplateAttr} ;
  //=====================================================================
  private boolean TemplateAttr()
    {
      if (saved(TemplateAttr)) return reuse();
      while (TemplateAttr_0());
      sem.TemplateAttr();
      return accept(TemplateAttr);
    }
  
  //-------------------------------------------------------------------
  //  TemplateAttr_0 = !(SEP / RT) RichTextComponent
  //-------------------------------------------------------------------
  private boolean TemplateAttr_0()
    {
      if (savedInner(TemplateAttr_0)) return reuseInner();
      if (!TemplateAttr_1()) return rejectInner(TemplateAttr_0);
      if (!RichTextComponent()) return rejectInner(TemplateAttr_0);
      return acceptInner(TemplateAttr_0);
    }
  
  //-------------------------------------------------------------------
  //  TemplateAttr_1 = !(SEP / RT)
  //-------------------------------------------------------------------
  private boolean TemplateAttr_1()
    {
      if (savedInner(TemplateAttr_1)) return reusePred();
      if (TemplateAttr_2()) return rejectNot(TemplateAttr_1);
      return acceptNot(TemplateAttr_1);
    }
  
  //-------------------------------------------------------------------
  //  TemplateAttr_2 = SEP / RT
  //-------------------------------------------------------------------
  private boolean TemplateAttr_2()
    {
      if (savedInner(TemplateAttr_2)) return reuseInner();
      if (SEP()) return acceptInner(TemplateAttr_2);
      if (RT()) return acceptInner(TemplateAttr_2);
      return rejectInner(TemplateAttr_2);
    }
  
  //=====================================================================
  //  ItemNo = "[" _++ "]" Space {ItemNo} ;
  //=====================================================================
  private boolean ItemNo()
    {
      if (saved(ItemNo)) return reuse();
      if (!next('[',$Term8)) return reject(ItemNo);
      if (next(']',$Term17)) return reject(ItemNo);
      do if (!next($Term45)) return reject(ItemNo);
        while (!next(']',$Term17));
      Space();
      sem.ItemNo();
      return accept(ItemNo);
    }
  
  //=====================================================================
  //  BR = "<br" Space "/>" ;
  //=====================================================================
  private boolean BR()
    {
      if (saved(BR)) return reuse();
      if (!next("<br",$Term50)) return reject(BR);
      Space();
      if (!next("/>",$Term39)) return reject(BR);
      return accept(BR);
    }
  
  //=====================================================================
  //  Comment = CommentStart _++ CommentEnd Space ;
  //=====================================================================
  private boolean Comment()
    {
      if (saved(Comment)) return reuse();
      if (!CommentStart()) return reject(Comment);
      if (CommentEnd()) return reject(Comment);
      do if (!next($Term0)) return reject(Comment);
        while (!CommentEnd());
      Space();
      return accept(Comment);
    }
  
  //=====================================================================
  //  CommentStart = "<!--" Space ;
  //=====================================================================
  private boolean CommentStart()
    {
      if (saved(CommentStart)) return reuse();
      if (!next("<!--",$Term32)) return reject(CommentStart);
      Space();
      return accept(CommentStart);
    }
  
  //=====================================================================
  //  CommentEnd = "-->" Space ;
  //=====================================================================
  private boolean CommentEnd()
    {
      if (saved(CommentEnd)) return reuse();
      if (!next("-->",$Term4)) return reject(CommentEnd);
      Space();
      return accept(CommentEnd);
    }
  
  //=====================================================================
  //  Line = _++ EOL ;
  //=====================================================================
  private boolean Line()
    {
      if (saved(Line)) return reuse();
      if (EOL()) return reject(Line);
      do if (!next($Term22)) return reject(Line);
        while (!EOL());
      return accept(Line);
    }
  
  //=====================================================================
  //  BadLine = _++ EOL ;
  //=====================================================================
  private boolean BadLine()
    {
      if (saved(BadLine)) return reuse();
      if (EOL()) return reject(BadLine);
      do if (!next($Term22)) return reject(BadLine);
        while (!EOL());
      return accept(BadLine);
    }
  
  //=====================================================================
  //  EmptyLine = Space EOL ;
  //=====================================================================
  private boolean EmptyLine()
    {
      if (saved(EmptyLine)) return reuse();
      Space();
      if (!EOL()) return reject(EmptyLine);
      return accept(EmptyLine);
    }
  
  //=====================================================================
  //  RestOfLine = _*+ EOL ;
  //=====================================================================
  private boolean RestOfLine()
    {
      if (saved(RestOfLine)) return reuse();
      while (!EOL())
        if (!next($Term37)) return reject(RestOfLine);
      return accept(RestOfLine);
    }
  
  //=====================================================================
  //  Digit = [0-9] ;
  //=====================================================================
  private boolean Digit()
    {
      if (saved(Digit)) return reuse();
      if (!nextIn('0','9',$Term53)) return reject(Digit);
      return accept(Digit);
    }
  
  //=====================================================================
  //  OptDigit = Digit? ;
  //=====================================================================
  private boolean OptDigit()
    {
      if (saved(OptDigit)) return reuse();
      Digit();
      return accept(OptDigit);
    }
  
  //=====================================================================
  //  Number = Digit+ ;
  //=====================================================================
  private boolean Number()
    {
      if (saved(Number)) return reuse();
      if (!Digit()) return reject(Number);
      while (Digit());
      return accept(Number);
    }
  
  //=====================================================================
  //  Letter = [a-z] / [A-Z] / [äÄüÜöÖß] ;
  //=====================================================================
  private boolean Letter()
    {
      if (saved(Letter)) return reuse();
      if (nextIn('a','z',$Term20)) return accept(Letter);
      if (nextIn('A','Z',$Term7)) return accept(Letter);
      if (nextIn("\u00e4\u00c4\u00fc\u00dc\u00f6\u00d6\u00df",$Term36)) return accept(Letter);
      return reject(Letter);
    }
  
  //=====================================================================
  //  Word = Letter (Letter / [-'])* ;
  //=====================================================================
  private boolean Word()
    {
      if (saved(Word)) return reuse();
      if (!Letter()) return reject(Word);
      while (Word_0());
      return accept(Word);
    }
  
  //-------------------------------------------------------------------
  //  Word_0 = Letter / [-']
  //-------------------------------------------------------------------
  private boolean Word_0()
    {
      if (savedInner(Word_0)) return reuseInner();
      if (Letter()) return acceptInner(Word_0);
      if (nextIn("-'",$Term29)) return acceptInner(Word_0);
      return rejectInner(Word_0);
    }
  
  //=====================================================================
  //  Phrase = Word (Space Word)* ;
  //=====================================================================
  private boolean Phrase()
    {
      if (saved(Phrase)) return reuse();
      if (!Word()) return reject(Phrase);
      while (Phrase_0());
      return accept(Phrase);
    }
  
  //-------------------------------------------------------------------
  //  Phrase_0 = Space Word
  //-------------------------------------------------------------------
  private boolean Phrase_0()
    {
      if (savedInner(Phrase_0)) return reuseInner();
      Space();
      if (!Word()) return rejectInner(Phrase_0);
      return acceptInner(Phrase_0);
    }
  
  //=====================================================================
  //  Space = " "* ;
  //=====================================================================
  private boolean Space()
    {
      if (saved(Space)) return reuse();
      while (next(' ',$Term28));
      return accept(Space);
    }
  
  //=====================================================================
  //  COMMA = "," Space ;
  //=====================================================================
  private boolean COMMA()
    {
      if (saved(COMMA)) return reuse();
      if (!next(',',$Term63)) return reject(COMMA);
      Space();
      return accept(COMMA);
    }
  
  //=====================================================================
  //  SEMICOLON = ";" Space ;
  //=====================================================================
  private boolean SEMICOLON()
    {
      if (saved(SEMICOLON)) return reuse();
      if (!next(';',$Term34)) return reject(SEMICOLON);
      Space();
      return accept(SEMICOLON);
    }
  
  //=====================================================================
  //  EOF = !_ ;
  //=====================================================================
  private boolean EOF()
    {
      if (saved(EOF)) return reuse();
      if (!aheadNot($Term14)) return reject(EOF);
      return accept(EOF);
    }
  
  //=====================================================================
  //  EOL = [\r\n]+ / EOF ;
  //=====================================================================
  private boolean EOL()
    {
      if (saved(EOL)) return reuse();
      if (EOL_0()) return accept(EOL);
      if (EOF()) return accept(EOL);
      return reject(EOL);
    }
  
  //-------------------------------------------------------------------
  //  EOL_0 = [\r\n]+
  //-------------------------------------------------------------------
  private boolean EOL_0()
    {
      if (savedInner(EOL_0)) return reuseInner();
      if (!nextIn("\r\n",$Term59)) return rejectInner(EOL_0);
      while (nextIn("\r\n",$Term59));
      return acceptInner(EOL_0);
    }
  
  //=======================================================================
  //
  //  Cache objects
  //
  //=======================================================================
  
  final Cache Dokument = new Cache("Dokument","Dokument");
  final Cache Eintrag = new Cache("Eintrag","Eintrag");
  final Cache OtherLangEintrag = new Cache("OtherLangEintrag","OtherLangEintrag");
  final Cache DeEintrag = new Cache("DeEintrag","DeEintrag");
  final Cache DeSpracheKopf = new Cache("DeSpracheKopf","DeSpracheKopf");
  final Cache DeSpracheTemplate = new Cache("DeSpracheTemplate","DeSpracheTemplate");
  final Cache Lemma = new Cache("Lemma","Lemma");
  final Cache DeWortart = new Cache("DeWortart","DeWortart");
  final Cache WortartKopf = new Cache("WortartKopf","WortartKopf");
  final Cache WortartBody = new Cache("WortartBody","WortartBody");
  final Cache UnknownWortartKopf = new Cache("UnknownWortartKopf","UnknownWortartKopf");
  final Cache WortartTemplate = new Cache("WortartTemplate","WortartTemplate");
  final Cache SubstantivKopf = new Cache("SubstantivKopf","SubstantivKopf");
  final Cache SubstantivTemplate = new Cache("SubstantivTemplate","SubstantivTemplate");
  final Cache SubstantivAttributes = new Cache("SubstantivAttributes","SubstantivAttributes");
  final Cache SubstantivAttribute = new Cache("SubstantivAttribute","SubstantivAttribute");
  final Cache FlexionTable = new Cache("FlexionTable","FlexionTable");
  final Cache FlexionTableKopf = new Cache("FlexionTableKopf","FlexionTableKopf");
  final Cache FlexionForm = new Cache("FlexionForm","FlexionForm");
  final Cache NomSg = new Cache("NomSg","NomSg");
  final Cache NomPl = new Cache("NomPl","NomPl");
  final Cache GenSg = new Cache("GenSg","GenSg");
  final Cache GenPl = new Cache("GenPl","GenPl");
  final Cache DatSg = new Cache("DatSg","DatSg");
  final Cache DatPl = new Cache("DatPl","DatPl");
  final Cache AkkSg = new Cache("AkkSg","AkkSg");
  final Cache AkkPl = new Cache("AkkPl","AkkPl");
  final Cache FlexionVariantList = new Cache("FlexionVariantList","FlexionVariantList");
  final Cache Gender = new Cache("Gender","Gender");
  final Cache GenderTemplateArgument = new Cache("GenderTemplateArgument","GenderTemplateArgument");
  final Cache MiddleSection = new Cache("MiddleSection","MiddleSection");
  final Cache MeaningsTextbaustein = new Cache("MeaningsTextbaustein","MeaningsTextbaustein");
  final Cache MeaningsKopf = new Cache("MeaningsKopf","MeaningsKopf");
  final Cache MeaningList = new Cache("MeaningList","MeaningList");
  final Cache Meaning = new Cache("Meaning","Meaning");
  final Cache MeaningLvl = new Cache("MeaningLvl","MeaningLvl");
  final Cache TranslationsSection = new Cache("TranslationsSection","TranslationsSection");
  final Cache TranslationsKopf = new Cache("TranslationsKopf","TranslationsKopf");
  final Cache TranslationsTable = new Cache("TranslationsTable","TranslationsTable");
  final Cache TranslationsTableKopf = new Cache("TranslationsTableKopf","TranslationsTableKopf");
  final Cache LangTranslations = new Cache("LangTranslations","LangTranslations");
  final Cache LangLvl = new Cache("LangLvl","LangLvl");
  final Cache Lang = new Cache("Lang","Lang");
  final Cache TranslationMeaning = new Cache("TranslationMeaning","TranslationMeaning");
  final Cache Translation = new Cache("Translation","Translation");
  final Cache TranslationDetails = new Cache("TranslationDetails","TranslationDetails");
  final Cache UeTemplate = new Cache("UeTemplate","UeTemplate");
  final Cache UetTemplate = new Cache("UetTemplate","UetTemplate");
  final Cache DialectTable = new Cache("DialectTable","DialectTable");
  final Cache KOPF2 = new Cache("KOPF2","KOPF2");
  final Cache KOPF3 = new Cache("KOPF3","KOPF3");
  final Cache KOPF4 = new Cache("KOPF4","KOPF4");
  final Cache KopfStart = new Cache("KopfStart","KopfStart");
  final Cache SEP = new Cache("SEP","SEP");
  final Cache TextbausteinEnd = new Cache("TextbausteinEnd","TextbausteinEnd");
  final Cache RichTextComponent = new Cache("RichTextComponent","RichTextComponent");
  final Cache LL = new Cache("LL","LL");
  final Cache RL = new Cache("RL","RL");
  final Cache Link = new Cache("Link","Link");
  final Cache LinkAttr = new Cache("LinkAttr","LinkAttr");
  final Cache CursiveText = new Cache("CursiveText","CursiveText");
  final Cache LT = new Cache("LT","LT");
  final Cache RT = new Cache("RT","RT");
  final Cache Template = new Cache("Template","Template");
  final Cache TemplateAttr = new Cache("TemplateAttr","TemplateAttr");
  final Cache ItemNo = new Cache("ItemNo","ItemNo");
  final Cache BR = new Cache("BR","BR");
  final Cache Comment = new Cache("Comment","Comment");
  final Cache CommentStart = new Cache("CommentStart","CommentStart");
  final Cache CommentEnd = new Cache("CommentEnd","CommentEnd");
  final Cache Line = new Cache("Line","Line");
  final Cache BadLine = new Cache("BadLine","BadLine");
  final Cache EmptyLine = new Cache("EmptyLine","EmptyLine");
  final Cache RestOfLine = new Cache("RestOfLine","RestOfLine");
  final Cache Digit = new Cache("Digit","Digit");
  final Cache OptDigit = new Cache("OptDigit","OptDigit");
  final Cache Number = new Cache("Number","Number");
  final Cache Letter = new Cache("Letter","Letter");
  final Cache Word = new Cache("Word","Word");
  final Cache Phrase = new Cache("Phrase","Phrase");
  final Cache Space = new Cache("Space","Space");
  final Cache COMMA = new Cache("COMMA","COMMA");
  final Cache SEMICOLON = new Cache("SEMICOLON","SEMICOLON");
  final Cache EOF = new Cache("EOF","EOF");
  final Cache EOL = new Cache("EOL","EOL");
  
  final Cache Dokument_0 = new Cache("Dokument_0"); // !KOPF2 Line
  final Cache Dokument_1 = new Cache("Dokument_1","not KOPF2"); // !KOPF2
  final Cache OtherLangEintrag_0 = new Cache("OtherLangEintrag_0"); // !DeSpracheKopf Line
  final Cache OtherLangEintrag_1 = new Cache("OtherLangEintrag_1","not DeSpracheKopf"); // !DeSpracheKopf
  final Cache DeWortart_0 = new Cache("DeWortart_0"); // WortartKopf WortartBody
  final Cache DeWortart_1 = new Cache("DeWortart_1"); // UnknownWortartKopf Line*
  final Cache WortartBody_0 = new Cache("WortartBody_0"); // MiddleSection TranslationsSection?
  final Cache SubstantivAttributes_0 = new Cache("SubstantivAttributes_0"); // (","? Space SubstantivAttribute)+
  final Cache SubstantivAttributes_1 = new Cache("SubstantivAttributes_1"); // _++ KOPF3
  final Cache SubstantivAttributes_2 = new Cache("SubstantivAttributes_2"); // ","? Space SubstantivAttribute
  final Cache SubstantivAttribute_0 = new Cache("SubstantivAttribute_0"); // "''adjektivische Deklination" ","? "''"
  final Cache FlexionVariantList_0 = new Cache("FlexionVariantList_0"); // Space Phrase (BR Phrase)*
  final Cache FlexionVariantList_1 = new Cache("FlexionVariantList_1"); // Space "\u2014" Space
  final Cache FlexionVariantList_2 = new Cache("FlexionVariantList_2"); // (!EOL _)*
  final Cache FlexionVariantList_3 = new Cache("FlexionVariantList_3"); // BR Phrase
  final Cache FlexionVariantList_4 = new Cache("FlexionVariantList_4"); // !EOL _
  final Cache FlexionVariantList_5 = new Cache("FlexionVariantList_5","not EOL"); // !EOL
  final Cache GenderTemplateArgument_0 = new Cache("GenderTemplateArgument_0"); // "f" ("m" / "n")
  final Cache GenderTemplateArgument_1 = new Cache("GenderTemplateArgument_1"); // "n" ("m" / "f")
  final Cache MiddleSection_0 = new Cache("MiddleSection_0"); // !TranslationsKopf (FlexionTable / MeaningsTextbaustein / Line)
  final Cache MiddleSection_1 = new Cache("MiddleSection_1","not TranslationsKopf"); // !TranslationsKopf
  final Cache MeaningList_0 = new Cache("MeaningList_0"); // !TextbausteinEnd (Meaning / Line)
  final Cache MeaningList_1 = new Cache("MeaningList_1","not TextbausteinEnd"); // !TextbausteinEnd
  final Cache TranslationsSection_0 = new Cache("TranslationsSection_0"); // !TranslationsTableKopf Line
  final Cache TranslationsSection_1 = new Cache("TranslationsSection_1"); // !KopfStart Line
  final Cache TranslationsSection_2 = new Cache("TranslationsSection_2","not TranslationsTableKopf"); // !TranslationsTableKopf
  final Cache TranslationsSection_3 = new Cache("TranslationsSection_3","not KopfStart"); // !KopfStart
  final Cache TranslationsTable_0 = new Cache("TranslationsTable_0"); // LangTranslations / DialectTable / !RT Line
  final Cache TranslationsTable_1 = new Cache("TranslationsTable_1"); // !RT Line
  final Cache TranslationsTable_2 = new Cache("TranslationsTable_2","not RT"); // !RT
  final Cache Translation_0 = new Cache("Translation_0"); // COMMA / SEMICOLON
  final Cache TranslationDetails_0 = new Cache("TranslationDetails_0"); // CursiveText / Link / !(ItemNo / UeTemplate / UetTemplate / COMMA / SEMICOLON / EOL) _
  final Cache TranslationDetails_1 = new Cache("TranslationDetails_1"); // !(ItemNo / UeTemplate / UetTemplate / COMMA / SEMICOLON / EOL) _
  final Cache TranslationDetails_2 = new Cache("TranslationDetails_2","not ItemNo / UeTemplate / UetTemplate / COMMA / SEMICOLON / EOL"); // !(ItemNo / UeTemplate / UetTemplate / COMMA / SEMICOLON / EOL)
  final Cache TranslationDetails_3 = new Cache("TranslationDetails_3"); // ItemNo / UeTemplate / UetTemplate / COMMA / SEMICOLON / EOL
  final Cache UeTemplate_0 = new Cache("UeTemplate_0"); // SEP TemplateAttr
  final Cache Link_0 = new Cache("Link_0"); // SEP LinkAttr
  final Cache LinkAttr_0 = new Cache("LinkAttr_0"); // !(SEP / RL) _
  final Cache LinkAttr_1 = new Cache("LinkAttr_1","not SEP / RL"); // !(SEP / RL)
  final Cache LinkAttr_2 = new Cache("LinkAttr_2"); // SEP / RL
  final Cache TemplateAttr_0 = new Cache("TemplateAttr_0"); // !(SEP / RT) RichTextComponent
  final Cache TemplateAttr_1 = new Cache("TemplateAttr_1","not SEP / RT"); // !(SEP / RT)
  final Cache TemplateAttr_2 = new Cache("TemplateAttr_2"); // SEP / RT
  final Cache Word_0 = new Cache("Word_0"); // Letter / [-']
  final Cache Phrase_0 = new Cache("Phrase_0"); // Space Word
  final Cache EOL_0 = new Cache("EOL_0"); // [\r\n]+
  
  final Cache $Term0 = new Cache("_");
  final Cache $Term1 = new Cache("\"\u00dc-Tabelle\"");
  final Cache $Term2 = new Cache("\"Nominativ Plural\"");
  final Cache $Term3 = new Cache("\"|\"");
  final Cache $Term4 = new Cache("\"-->\"");
  final Cache $Term5 = new Cache("\"Substantiv\"");
  final Cache $Term6 = new Cache("\"==\"");
  final Cache $Term7 = new Cache("[A-Z]");
  final Cache $Term8 = new Cache("\"[\"");
  final Cache $Term9 = new Cache("\"u\"");
  final Cache $Term10 = new Cache("\"===\"");
  final Cache $Term11 = new Cache("\"(\"");
  final Cache $Term12 = new Cache("\"Wortart\"");
  final Cache $Term13 = new Cache("\"''\"");
  final Cache $Term14 = new Cache("_");
  final Cache $Term15 = new Cache("\"}}\"");
  final Cache $Term16 = new Cache("\"\u00dct?\"");
  final Cache $Term17 = new Cache("\"]\"");
  final Cache $Term18 = new Cache("\"Sprache\"");
  final Cache $Term19 = new Cache("\"\u00dc\"");
  final Cache $Term20 = new Cache("[a-z]");
  final Cache $Term21 = new Cache("\"*\"");
  final Cache $Term22 = new Cache("_");
  final Cache $Term23 = new Cache("\"{{\"");
  final Cache $Term24 = new Cache("\"Nominativ Singular\"");
  final Cache $Term25 = new Cache("\"|Dialekttabelle=\"");
  final Cache $Term26 = new Cache("\":\"");
  final Cache $Term27 = new Cache("\"\u00dc?\"");
  final Cache $Term28 = new Cache("\" \"");
  final Cache $Term29 = new Cache("[-']");
  final Cache $Term30 = new Cache("\"f\"");
  final Cache $Term31 = new Cache("\"Akkusativ Singular\"");
  final Cache $Term32 = new Cache("\"<!--\"");
  final Cache $Term33 = new Cache("\"Genitiv Singular\"");
  final Cache $Term34 = new Cache("\";\"");
  final Cache $Term35 = new Cache("\"]]\"");
  final Cache $Term36 = new Cache("[\u00e4\u00c4\u00fc\u00dc\u00f6\u00d6\u00df]");
  final Cache $Term37 = new Cache("_");
  final Cache $Term38 = new Cache("\"Akkusativ Plural\"");
  final Cache $Term39 = new Cache("\"/>\"");
  final Cache $Term40 = new Cache("\"m\"");
  final Cache $Term41 = new Cache("\"[[\"");
  final Cache $Term42 = new Cache("\"Dativ Singular\"");
  final Cache $Term43 = new Cache("\"mf\"");
  final Cache $Term44 = new Cache("\"====\"");
  final Cache $Term45 = new Cache("_");
  final Cache $Term46 = new Cache("\"Deutsch\"");
  final Cache $Term47 = new Cache("\"''\"");
  final Cache $Term48 = new Cache("\"n\"");
  final Cache $Term49 = new Cache("\"Bedeutungen\"");
  final Cache $Term50 = new Cache("\"<br\"");
  final Cache $Term51 = new Cache("\"=\"");
  final Cache $Term52 = new Cache("\"Genitiv Plural\"");
  final Cache $Term53 = new Cache("[0-9]");
  final Cache $Term54 = new Cache("\"\u00dct\"");
  final Cache $Term55 = new Cache("\"\u2014\"");
  final Cache $Term56 = new Cache("\"Deutsch Substantiv \u00dcbersicht\"");
  final Cache $Term57 = new Cache("\"\u00dcbersetzungen\"");
  final Cache $Term58 = new Cache("\"Dativ Plural\"");
  final Cache $Term59 = new Cache("[\r\n]");
  final Cache $Term60 = new Cache("\")\"");
  final Cache $Term61 = new Cache("_");
  final Cache $Term62 = new Cache("\"''adjektivische Deklination\"");
  final Cache $Term63 = new Cache("\",\"");
  
  //-------------------------------------------------------------------
  //  List of Cache objects
  //-------------------------------------------------------------------
  
  Cache[] cacheList =
  {
    Dokument,Eintrag,OtherLangEintrag,DeEintrag,DeSpracheKopf,
    DeSpracheTemplate,Lemma,DeWortart,WortartKopf,WortartBody,
    UnknownWortartKopf,WortartTemplate,SubstantivKopf,
    SubstantivTemplate,SubstantivAttributes,SubstantivAttribute,
    FlexionTable,FlexionTableKopf,FlexionForm,NomSg,NomPl,GenSg,GenPl,
    DatSg,DatPl,AkkSg,AkkPl,FlexionVariantList,Gender,
    GenderTemplateArgument,MiddleSection,MeaningsTextbaustein,
    MeaningsKopf,MeaningList,Meaning,MeaningLvl,TranslationsSection,
    TranslationsKopf,TranslationsTable,TranslationsTableKopf,
    LangTranslations,LangLvl,Lang,TranslationMeaning,Translation,
    TranslationDetails,UeTemplate,UetTemplate,DialectTable,KOPF2,
    KOPF3,KOPF4,KopfStart,SEP,TextbausteinEnd,RichTextComponent,LL,RL,
    Link,LinkAttr,CursiveText,LT,RT,Template,TemplateAttr,ItemNo,BR,
    Comment,CommentStart,CommentEnd,Line,BadLine,EmptyLine,RestOfLine,
    Digit,OptDigit,Number,Letter,Word,Phrase,Space,COMMA,SEMICOLON,
    EOF,EOL,Dokument_0,Dokument_1,OtherLangEintrag_0,
    OtherLangEintrag_1,DeWortart_0,DeWortart_1,WortartBody_0,
    SubstantivAttributes_0,SubstantivAttributes_1,
    SubstantivAttributes_2,SubstantivAttribute_0,FlexionVariantList_0,
    FlexionVariantList_1,FlexionVariantList_2,FlexionVariantList_3,
    FlexionVariantList_4,FlexionVariantList_5,
    GenderTemplateArgument_0,GenderTemplateArgument_1,MiddleSection_0,
    MiddleSection_1,MeaningList_0,MeaningList_1,TranslationsSection_0,
    TranslationsSection_1,TranslationsSection_2,TranslationsSection_3,
    TranslationsTable_0,TranslationsTable_1,TranslationsTable_2,
    Translation_0,TranslationDetails_0,TranslationDetails_1,
    TranslationDetails_2,TranslationDetails_3,UeTemplate_0,Link_0,
    LinkAttr_0,LinkAttr_1,LinkAttr_2,TemplateAttr_0,TemplateAttr_1,
    TemplateAttr_2,Word_0,Phrase_0,EOL_0,$Term0,$Term1,$Term2,$Term3,
    $Term4,$Term5,$Term6,$Term7,$Term8,$Term9,$Term10,$Term11,$Term12,
    $Term13,$Term14,$Term15,$Term16,$Term17,$Term18,$Term19,$Term20,
    $Term21,$Term22,$Term23,$Term24,$Term25,$Term26,$Term27,$Term28,
    $Term29,$Term30,$Term31,$Term32,$Term33,$Term34,$Term35,$Term36,
    $Term37,$Term38,$Term39,$Term40,$Term41,$Term42,$Term43,$Term44,
    $Term45,$Term46,$Term47,$Term48,$Term49,$Term50,$Term51,$Term52,
    $Term53,$Term54,$Term55,$Term56,$Term57,$Term58,$Term59,$Term60,
    $Term61,$Term62,$Term63
  };
}
